;;; chat-coding-acceptance.el --- Final coding acceptance -*- lexical-binding: t; -*-

;; Copyright (C) 2026 chat.el contributors
;; License: 1PL (One Public License) - https://license.pub/1pl/

;;; Commentary:

;; Strict M17 acceptance aggregation and a reproducible repository benchmark.
;; Source Eval records, lifecycle facts, and repo maps remain authoritative.

;;; Code:

(require 'cl-lib)
(require 'json)
(require 'seq)
(require 'subr-x)
(require 'chat-eval)
(require 'chat-repo-map)
(require 'chat-context-code)
(require 'chat-code)

(defgroup chat-coding-acceptance nil
  "Final coding capability acceptance."
  :group 'chat)

(defcustom chat-coding-acceptance-query-repetitions 30
  "Warm query and context-build repetitions in the performance benchmark."
  :type 'integer :group 'chat-coding-acceptance)

(defcustom chat-coding-acceptance-file-count 10000
  "Source files generated by the standalone performance benchmark."
  :type 'integer :group 'chat-coding-acceptance)

(defconst chat-coding-acceptance-failure-kinds
  '(model-ability context-omission tool-error verification-error
                  permission-block infrastructure)
  "Closed failure taxonomy for coding trials.")

(cl-defstruct (chat-coding-acceptance-gate
               (:constructor chat-coding-acceptance-gate-create))
  name status expected actual evidence)

(defun chat-coding-acceptance--metadata (result)
  "Return executor metadata from coding RESULT."
  (alist-get 'executor (chat-eval-result-metadata result)))

(defun chat-coding-acceptance--number (key data)
  "Return numeric KEY from alist DATA, defaulting to zero."
  (let ((value (alist-get key data)))
    (if (numberp value) value 0)))

(defun chat-coding-acceptance--field (data key)
  "Read KEY from JSON alist or keyword plist DATA."
  (when (listp data)
    (or (alist-get key data)
        (plist-get data (intern (concat ":" (symbol-name key)))))))

(defun chat-coding-acceptance-classify-failure (result)
  "Classify failed coding RESULT into one public failure kind."
  (when (not (eq (chat-eval-result-status result) 'passed))
    (let* ((executor (chat-coding-acceptance--metadata result))
           (checks (chat-eval-result-checks result))
           (text
            (downcase
             (mapconcat
              (lambda (check)
                (format "%s %s %s"
                        (chat-eval-check-name check)
                        (chat-eval-check-actual check)
                        (or (chat-eval-check-detail check) "")))
              (seq-remove #'chat-eval-check-passed checks) " "))))
      (cond
       ((or (memq (chat-eval-result-status result) '(blocked cancelled))
            (> (chat-coding-acceptance--number 'approvalCount executor) 0)
            (string-match-p "\\(?:permission\\|approval\\|blocked\\|denied\\)" text))
        'permission-block)
       ((> (chat-coding-acceptance--number 'toolErrorCount executor) 0)
        'tool-error)
       ((string-match-p "\\(?:fixture-setup\\|workspace-cleanup\\|executor-status\\)" text)
        'infrastructure)
       ((string-match-p "\\(?:judge\\|verification\\|test\\|build\\|lint\\|typecheck\\)" text)
        'verification-error)
       ((string-match-p "\\(?:missing context\\|wrong file\\|not found\\|omitted\\)" text)
        'context-omission)
       (t 'model-ability)))))

(defun chat-coding-acceptance-failure-summary (results)
  "Return deterministic counts by failure kind for RESULTS."
  (mapcar
   (lambda (kind)
     (cons kind
           (cl-count kind results
                     :key #'chat-coding-acceptance-classify-failure)))
   chat-coding-acceptance-failure-kinds))

(defun chat-coding-acceptance-load-result-directory (directory)
  "Load coding Eval results from DIRECTORY in deterministic order."
  (let (results)
    (when (file-directory-p directory)
      (dolist (file (sort (directory-files directory t "\\.json\\'")
                          #'string<))
        (condition-case nil
            (let ((result (chat-eval-load-result file)))
              (when (string-prefix-p
                     "coding/" (chat-eval-result-scenario-id result))
                (push result results)))
          (error nil))))
    (nreverse results)))

(defun chat-coding-acceptance--task-id (result)
  "Return stable task id from coding RESULT."
  (chat-coding-acceptance--field
   (chat-eval-result-metadata result) 'taskId))

(defun chat-coding-acceptance--group-by-task (results)
  "Return task-id table for RESULTS."
  (let ((table (make-hash-table :test 'equal)))
    (dolist (result results table)
      (when-let* ((id (chat-coding-acceptance--task-id result)))
        (puthash id (cons result (gethash id table)) table)))))

(defun chat-coding-acceptance--valid-results (results)
  "Return RESULTS excluding infrastructure-invalid trials."
  (seq-remove
   (lambda (result)
     (eq (chat-coding-acceptance-classify-failure result) 'infrastructure))
   results))

(defun chat-coding-acceptance--success-rate (results)
  "Return passed fraction for RESULTS, or nil when empty."
  (when results
    (/ (float (cl-count 'passed results :key #'chat-eval-result-status))
       (length results))))

(defun chat-coding-acceptance--trial-identity (result)
  "Return comparison identity for coding RESULT."
  (let* ((metadata (chat-eval-result-metadata result))
         (executor (chat-coding-acceptance--field metadata 'executor)))
    (list
     (chat-coding-acceptance--task-id result)
     (chat-eval-result-scenario-revision result)
     (chat-eval-result-fixture-digest result)
     (chat-coding-acceptance--field executor 'model)
     (chat-coding-acceptance--field executor 'modelCapabilitySnapshot))))

(defun chat-coding-acceptance--compatible-identities-p (baseline current)
  "Return non-nil when BASELINE and CURRENT have comparable task identities."
  (let ((left (chat-coding-acceptance--group-by-task baseline))
        (right (chat-coding-acceptance--group-by-task current))
        compatible)
    (setq compatible (= (hash-table-count left) (hash-table-count right)))
    (maphash
     (lambda (task trials)
       (let* ((other (gethash task right))
              (left-identities
               (delete-dups
                (mapcar (lambda (trial)
                          (cdr (chat-coding-acceptance--trial-identity trial)))
                        trials)))
              (right-identities
               (and other
                    (delete-dups
                     (mapcar
                      (lambda (trial)
                        (cdr (chat-coding-acceptance--trial-identity trial)))
                      other)))))
         (unless (and (= (length left-identities) 1)
                      (= (length right-identities) 1)
                      (equal (car left-identities)
                             (car right-identities)))
           (setq compatible nil))))
     left)
    compatible))

(defun chat-coding-acceptance--five-by-thirty-p (results)
  "Return non-nil when RESULTS contain exactly five trials for 30 tasks."
  (let ((table (chat-coding-acceptance--group-by-task results))
        (valid t))
    (maphash (lambda (_task trials)
               (unless (= (length trials) 5) (setq valid nil)))
             table)
    (and valid (= (hash-table-count table) 30) (= (length results) 150))))

(defun chat-coding-acceptance--out-of-scope-count (results)
  "Return aggregate out-of-scope edit count for RESULTS."
  (apply
   #'+ 0
   (mapcar
    (lambda (result)
      (length (or (chat-coding-acceptance--field
                   (chat-eval-result-metadata result) 'outOfScopeFiles)
                  nil)))
    results)))

(defun chat-coding-acceptance--unverified-pass-count (results)
  "Return passed trials without a deterministic judge check."
  (cl-count-if
   (lambda (result)
     (and (eq (chat-eval-result-status result) 'passed)
          (null
           (seq-remove
            (lambda (check)
              (member (chat-eval-check-name check)
                      '("executor-status" "allowed-paths" "workspace-cleanup")))
            (chat-eval-result-checks result)))))
   results))

(defun chat-coding-acceptance--input-tokens (result)
  "Return trusted input token count from RESULT, or nil."
  (let* ((executor (chat-coding-acceptance--metadata result))
         (usage (chat-coding-acceptance--field executor 'tokenUsage)))
    (or (chat-coding-acceptance--field usage 'input_tokens)
        (chat-coding-acceptance--field usage 'input-tokens)
        (chat-coding-acceptance--field usage 'prompt_tokens))))

(defun chat-coding-acceptance--task-tags (result)
  "Return normalized task tags from RESULT."
  (mapcar (lambda (tag) (downcase (format "%s" tag)))
          (or (chat-coding-acceptance--field
               (chat-eval-result-metadata result) 'taskTags)
              nil)))

(defun chat-coding-acceptance--large-repo-token-gate (baseline current)
  "Return the large-repository token gate for BASELINE and CURRENT."
  (let* ((baseline-large
          (seq-filter
           (lambda (result)
             (and (eq (chat-eval-result-status result) 'passed)
                  (member "large-repo"
                          (chat-coding-acceptance--task-tags result))))
           baseline))
         (current-large
          (seq-filter
           (lambda (result)
             (and (eq (chat-eval-result-status result) 'passed)
                  (member "large-repo"
                          (chat-coding-acceptance--task-tags result))))
           current))
         (baseline-usage
          (delq nil (mapcar #'chat-coding-acceptance--input-tokens
                            baseline-large)))
         (current-usage
          (delq nil (mapcar #'chat-coding-acceptance--input-tokens
                            current-large)))
         (complete
          (and baseline-large current-large
               (= (length baseline-large) (length baseline-usage))
               (= (length current-large) (length current-usage))
               (seq-every-p (lambda (value)
                              (and (numberp value) (> value 0)))
                            (append baseline-usage current-usage))))
         (baseline-median
          (and complete (chat-coding-acceptance--median baseline-usage)))
         (current-median
          (and complete (chat-coding-acceptance--median current-usage))))
    (chat-coding-acceptance-gate-create
     :name "live-eval-large-repo-token-budget"
     :status
     (if (not complete)
         'blocked
       (if (<= current-median (* 0.85 baseline-median))
           'passed
         'failed))
     :expected "large-repo median input tokens reduced >=15%"
     :actual
     (if complete
         (format "baseline=%s current=%s" baseline-median current-median)
       (format "baseline=%d/%d current=%d/%d usage samples"
               (length baseline-usage) (length baseline-large)
               (length current-usage) (length current-large)))
     :evidence
     (unless complete
       "Add fixed large-repo tagged trials with trusted usage for both configurations."))))

(defun chat-coding-acceptance--median (values)
  "Return median of numeric VALUES."
  (when values
    (let* ((ordered (sort (copy-sequence values) #'<))
           (count (length ordered))
           (middle (/ count 2)))
      (if (cl-oddp count)
          (nth middle ordered)
        (/ (+ (nth (1- middle) ordered) (nth middle ordered)) 2.0)))))

(defun chat-coding-acceptance-live-gates (baseline current)
  "Return final live-Eval gates comparing BASELINE with CURRENT."
  (if (or (null baseline) (null current))
      (list
       (chat-coding-acceptance-gate-create
        :name "live-eval-comparison" :status 'blocked
        :expected "M9 and M17 result sets"
        :actual "missing"
        :evidence "Run 30 tasks five times for both comparable configurations.")
       (chat-coding-acceptance--large-repo-token-gate baseline current))
    (let* ((baseline-valid (chat-coding-acceptance--valid-results baseline))
           (current-valid (chat-coding-acceptance--valid-results current))
           (baseline-rate
            (chat-coding-acceptance--success-rate baseline-valid))
           (current-rate
            (chat-coding-acceptance--success-rate current-valid))
           (usage (delq nil (mapcar #'chat-coding-acceptance--input-tokens
                                    current-valid)))
           (baseline-usage
            (delq nil (mapcar #'chat-coding-acceptance--input-tokens
                              baseline-valid)))
           (missing-usage
            (if current-valid
                (- 1.0 (/ (float (length usage)) (length current-valid)))
              1.0))
           (baseline-missing-usage
            (if baseline-valid
                (- 1.0
                   (/ (float (length baseline-usage))
                      (length baseline-valid)))
              1.0)))
      (list
       (chat-coding-acceptance-gate-create
        :name "live-eval-sample"
        :status (if (and
                     (chat-coding-acceptance--five-by-thirty-p baseline-valid)
                     (chat-coding-acceptance--five-by-thirty-p current-valid))
                    'passed 'failed)
        :expected "30 tasks x 5 for baseline and current"
        :actual (format "raw=%d/%d valid=%d/%d"
                        (length baseline) (length current)
                        (length baseline-valid) (length current-valid)))
       (chat-coding-acceptance-gate-create
        :name "live-eval-identity"
        :status (if (chat-coding-acceptance--compatible-identities-p
                     baseline current) 'passed 'failed)
        :expected "same task revision, fixture, model, and capability snapshot"
        :actual "compared")
       (chat-coding-acceptance-gate-create
        :name "live-eval-success-floor"
        :status (if (and current-rate (>= current-rate 0.80)) 'passed 'failed)
        :expected ">=80%" :actual current-rate)
       (chat-coding-acceptance-gate-create
        :name "live-eval-no-regression"
        :status (if (and baseline-rate current-rate
                         (>= current-rate baseline-rate)) 'passed 'failed)
        :expected baseline-rate :actual current-rate)
       (chat-coding-acceptance-gate-create
        :name "live-eval-target-or-improvement"
        :status (if (and baseline-rate current-rate
                         (or (>= current-rate 0.90)
                             (>= (- current-rate baseline-rate) 0.15)))
                    'passed 'failed)
        :expected ">=90% or +15 percentage points" :actual current-rate)
       (chat-coding-acceptance-gate-create
        :name "live-eval-scope"
        :status (if (zerop (chat-coding-acceptance--out-of-scope-count current))
                    'passed 'failed)
        :expected 0 :actual (chat-coding-acceptance--out-of-scope-count current))
       (chat-coding-acceptance-gate-create
        :name "live-eval-verification-evidence"
        :status (if (zerop (chat-coding-acceptance--unverified-pass-count current))
                    'passed 'failed)
        :expected 0 :actual (chat-coding-acceptance--unverified-pass-count current))
       (chat-coding-acceptance-gate-create
        :name "live-eval-token-coverage"
        :status (if (and (<= baseline-missing-usage 0.05)
                         (<= missing-usage 0.05))
                    'passed 'blocked)
        :expected "missing <=5% in baseline and current"
        :actual `((baseline . ,baseline-missing-usage)
                  (current . ,missing-usage)))
       (chat-coding-acceptance-gate-create
        :name "live-eval-input-token-budget"
        :status
        (if (and baseline-usage usage
                 (<= baseline-missing-usage 0.05)
                 (<= missing-usage 0.05))
            (if (<= (chat-coding-acceptance--median usage)
                    (* 1.10 (chat-coding-acceptance--median baseline-usage)))
                'passed 'failed)
          'blocked)
        :expected "current median <=110% of baseline"
        :actual (chat-coding-acceptance--median usage))
       (chat-coding-acceptance--large-repo-token-gate baseline current)))))

(defun chat-coding-acceptance--gate-check (gate)
  "Convert acceptance GATE to an immutable Eval check."
  (chat-eval-check
   (chat-coding-acceptance-gate-name gate)
   (eq (chat-coding-acceptance-gate-status gate) 'passed)
   (chat-coding-acceptance-gate-expected gate)
   `((status . ,(chat-coding-acceptance-gate-status gate))
     (value . ,(chat-coding-acceptance-gate-actual gate)))
   (chat-coding-acceptance-gate-evidence gate)))

(defun chat-coding-acceptance-overall-status (gates)
  "Return strict overall status for GATES."
  (cond
   ((seq-some (lambda (gate)
                (eq (chat-coding-acceptance-gate-status gate) 'failed))
              gates)
    'failed)
   ((seq-some (lambda (gate)
                (eq (chat-coding-acceptance-gate-status gate) 'blocked))
              gates)
    'blocked)
   (t 'passed)))

(defun chat-coding-acceptance-record (gates &optional metadata)
  "Persist one immutable final acceptance result from GATES and METADATA."
  (unless (and (listp gates)
               (seq-every-p #'chat-coding-acceptance-gate-p gates))
    (error "Acceptance requires typed gates"))
  (chat-eval-record-result
   :scenario-id "acceptance/m17"
   :scenario-revision 1
   :category "coding/acceptance"
   :fixture-id "m9-m17-roadmap"
   :fixture-digest
   (secure-hash
    'sha256
    (prin1-to-string
     (mapcar (lambda (gate)
               (list (chat-coding-acceptance-gate-name gate)
                     (chat-coding-acceptance-gate-expected gate)))
             gates)))
   :status (chat-coding-acceptance-overall-status gates)
   :checks (mapcar #'chat-coding-acceptance--gate-check gates)
   :metadata metadata))

(defun chat-coding-acceptance--percentile (values percentile)
  "Return nearest-rank PERCENTILE from numeric VALUES."
  (when values
    (let* ((ordered (sort (copy-sequence values) #'<))
           (rank (max 1 (ceiling (* percentile (length ordered))))))
      (nth (1- rank) ordered))))

(defun chat-coding-acceptance--heap-bytes ()
  "Return a comparable approximation of live Emacs heap bytes."
  (garbage-collect)
  (apply
   #'+
   (mapcar
    (lambda (entry)
      (if (and (numberp (nth 1 entry)) (numberp (nth 2 entry)))
          (* (nth 1 entry) (nth 2 entry))
        0))
    (garbage-collect))))

(defun chat-coding-acceptance--write-fixture (root file-count)
  "Create FILE-COUNT deterministic source files below ROOT."
  (let* ((directory-count (max 1 (ceiling (/ file-count 100.0))))
         (written 0))
    (dotimes (directory directory-count)
      (let ((path (expand-file-name (format "src/%04d" directory) root)))
        (make-directory path t)
        (dotimes (file 100)
          (when (< written file-count)
            (with-temp-file
                (expand-file-name (format "f%03d.py" file) path)
              (insert (format "def symbol_%04d_%03d(): return %d\n"
                              directory file written)))
            (cl-incf written)))))
    written))

(defun chat-coding-acceptance--environment ()
  "Return bounded benchmark environment facts."
  `((system . ,(symbol-name system-type))
    (systemConfiguration . ,system-configuration)
    (emacsVersion . ,emacs-version)
    (host . ,(system-name))))

(defun chat-coding-acceptance--measure-warm
    (root target file-count repetitions)
  "Measure warm query and context paths for ROOT and TARGET."
  (let (query-ms context-ms)
    (dotimes (index repetitions)
      (let ((started (float-time)))
        (chat-repo-map-query
         root
         (list
          :query
          (format "symbol_%04d_%03d"
                  (% index (max 1 (ceiling (/ file-count 100.0))))
                  (% index 100))
          :token-budget 2000 :limit 5))
        (push (* 1000.0 (- (float-time) started)) query-ms)))
    (let ((session (chat-code-session-create
                    "Acceptance benchmark" root target)))
      (setf (chat-code-session-context-strategy session) 'focused)
      (dotimes (_ repetitions)
        (let ((started (float-time)))
          (chat-context-code-build session)
          (push (* 1000.0 (- (float-time) started)) context-ms))))
    (list :warm-query-p95-ms
          (chat-coding-acceptance--percentile query-ms 0.95)
          :context-build-p95-ms
          (chat-coding-acceptance--percentile context-ms 0.95))))

(cl-defun chat-coding-acceptance-benchmark
    (&key (file-count chat-coding-acceptance-file-count)
          (repetitions chat-coding-acceptance-query-repetitions)
          on-complete)
  "Benchmark index, increment, query, context build, and memory.

ON-COMPLETE receives a bounded result plist.  The fixture is temporary and
is removed before the callback runs."
  (unless (and (integerp file-count) (> file-count 0)
               (integerp repetitions) (>= repetitions 20))
    (error "Benchmark requires positive files and at least 20 repetitions"))
  (let* ((root (make-temp-file "chat-repo-benchmark-" t))
         (fixture-digest
          (secure-hash
           'sha256
           (format "repo-map-v1:%d:python-symbol-template" file-count)))
         (before-bytes (chat-coding-acceptance--heap-bytes))
         (cold-start (float-time))
         cancel cleaned)
    (cl-labels
        ((cleanup
          ()
          (unless cleaned
            (setq cleaned t)
            (when (file-directory-p root)
              (chat-repo-map-discard root)
              (delete-directory root t))))
         (incremental-complete
         (cold cold-ms incremental incremental-start target)
          (let* ((incremental-ms
                  (* 1000.0 (- (float-time) incremental-start)))
                 (warm
                  (chat-coding-acceptance--measure-warm
                   root target file-count repetitions))
                 (result
                  (append
                   (list
                    :environment (chat-coding-acceptance--environment)
                    :fixture-digest fixture-digest
                    :file-count file-count :repetitions repetitions
                    :cold-index-ms cold-ms :cold-result cold
                    :incremental-ms incremental-ms
                    :incremental-result incremental)
                   warm
                   (list
                    :heap-delta-bytes
                    (max 0 (- (chat-coding-acceptance--heap-bytes)
                              before-bytes))))))
            (cleanup)
            (when on-complete (funcall on-complete result))))
         (cold-complete
          (cold)
          (let* ((cold-ms (* 1000.0 (- (float-time) cold-start)))
                 (target (expand-file-name "src/0000/f000.py" root))
                 (incremental-start (float-time)))
            (with-temp-file target
              (insert "def symbol_0000_000(): return 2\n"))
            (setq
             cancel
             (chat-repo-map-update-paths-async
              root (list target)
              (lambda (incremental)
                (incremental-complete
                 cold cold-ms incremental incremental-start target)))))))
      (chat-coding-acceptance--write-fixture root file-count)
      (setq cancel (chat-repo-map-refresh-async root #'cold-complete))
      (lambda ()
        (when (functionp cancel) (funcall cancel))
        (cleanup)))))

(cl-defun chat-coding-acceptance-benchmark-sync
    (&key (file-count chat-coding-acceptance-file-count)
          (repetitions chat-coding-acceptance-query-repetitions)
          (timeout 120))
  "Run the repository benchmark synchronously within TIMEOUT seconds."
  (let (result cancel)
    (setq cancel
          (chat-coding-acceptance-benchmark
           :file-count file-count :repetitions repetitions
           :on-complete (lambda (value) (setq result value))))
    (let ((deadline (+ (float-time) timeout)))
      (while (and (null result) (< (float-time) deadline))
        (accept-process-output nil 0.01)))
    (or result
        (progn
          (when (functionp cancel) (funcall cancel))
          (error "Repository benchmark timed out")))))

(defun chat-coding-acceptance-performance-gates (benchmark)
  "Return strict performance gates from BENCHMARK."
  (let* ((cold (plist-get benchmark :cold-result))
         (incremental (plist-get benchmark :incremental-result))
         (files (plist-get benchmark :file-count))
         (slice (max (or (plist-get cold :max-slice-wall-ms)
                         (plist-get cold :max-slice-ms)
                         0.0)
                     (or (plist-get incremental :max-slice-wall-ms)
                         (plist-get incremental :max-slice-ms)
                         0.0)))
         (query (plist-get benchmark :warm-query-p95-ms)))
    (list
     (chat-coding-acceptance-gate-create
      :name "performance-file-count"
      :status (if (and (= files 10000)
                       (= (plist-get cold :files) 10000)) 'passed 'failed)
      :expected 10000 :actual (plist-get cold :files))
     (chat-coding-acceptance-gate-create
      :name "performance-main-loop-slice"
      :status (if (<= slice 50.0) 'passed 'failed)
      :expected "<=50ms" :actual slice)
     (chat-coding-acceptance-gate-create
      :name "performance-warm-query-p95"
      :status (if (<= query 200.0) 'passed 'failed)
      :expected "<=200ms" :actual query)
     (chat-coding-acceptance-gate-create
      :name "performance-incremental-update"
      :status (if (= (plist-get incremental :changed) 1) 'passed 'failed)
      :expected 1 :actual (plist-get incremental :changed)))))

(defun chat-coding-acceptance-compare-live
    (baseline-directory current-directory)
  "Record a strict comparison of live results in two directories."
  (interactive
   (list (read-directory-name "M9 baseline results: ")
         (read-directory-name "M17 current results: ")))
  (let* ((baseline
          (chat-coding-acceptance-load-result-directory baseline-directory))
         (current
          (chat-coding-acceptance-load-result-directory current-directory))
         (result
          (chat-coding-acceptance-record
           (chat-coding-acceptance-live-gates baseline current)
           `((baselineTrials . ,(length baseline))
             (currentTrials . ,(length current))
             (failureSummary .
                             ,(chat-coding-acceptance-failure-summary
                               current))))))
    (when (called-interactively-p 'interactive)
      (message "Live acceptance %s: %s"
               (chat-eval-result-status result)
               (chat-eval-result-id result)))
    result))

(defun chat-coding-acceptance-run-performance ()
  "Run and immutably record the standalone 10,000-file benchmark."
  (interactive)
  (let* ((benchmark (chat-coding-acceptance-benchmark-sync))
         (gates (chat-coding-acceptance-performance-gates benchmark))
         (result
          (chat-coding-acceptance-record
           gates
           `((kind . "performance")
             (environment . ,(plist-get benchmark :environment))
             (fixtureDigest . ,(plist-get benchmark :fixture-digest))
             (coldIndexMs . ,(plist-get benchmark :cold-index-ms))
             (incrementalMs . ,(plist-get benchmark :incremental-ms))
             (warmQueryP95Ms .
                             ,(plist-get benchmark :warm-query-p95-ms))
             (contextBuildP95Ms .
                                ,(plist-get benchmark
                                            :context-build-p95-ms))
             (heapDeltaBytes .
                             ,(plist-get benchmark :heap-delta-bytes))))))
    (when (called-interactively-p 'interactive)
      (message "Performance acceptance %s: %s"
               (chat-eval-result-status result)
               (chat-eval-result-id result)))
    result))

(cl-defun chat-coding-acceptance-run-final
    (&optional baseline-directory current-directory metadata)
  "Run and record the strict final acceptance gate set.

BASELINE-DIRECTORY and CURRENT-DIRECTORY contain immutable M9 and M17 live
Eval results.  Missing directories remain explicit blocked gates.  METADATA
adds bounded externally verified facts such as the canonical test count."
  (interactive
   (list
    (let ((value
           (read-string "M9 baseline results directory (blank if missing): ")))
      (unless (string-empty-p value) value))
    (let ((value
           (read-string "M17 current results directory (blank if missing): ")))
      (unless (string-empty-p value) value))))
  (let* ((benchmark (chat-coding-acceptance-benchmark-sync))
         (baseline
          (and baseline-directory
               (file-directory-p baseline-directory)
               (chat-coding-acceptance-load-result-directory
                baseline-directory)))
         (current
          (and current-directory
               (file-directory-p current-directory)
               (chat-coding-acceptance-load-result-directory
                current-directory)))
         (gates
          (append (chat-coding-acceptance-performance-gates benchmark)
                  (chat-coding-acceptance-live-gates baseline current)))
         (result
          (chat-coding-acceptance-record
           gates
           (append
            `((kind . "final")
              (baselineTrials . ,(length baseline))
              (currentTrials . ,(length current))
              (failureSummary .
                              ,(chat-coding-acceptance-failure-summary current))
              (environment . ,(plist-get benchmark :environment))
              (fixtureDigest . ,(plist-get benchmark :fixture-digest))
              (coldIndexMs . ,(plist-get benchmark :cold-index-ms))
              (incrementalMs . ,(plist-get benchmark :incremental-ms))
              (warmQueryP95Ms .
                                ,(plist-get benchmark :warm-query-p95-ms))
              (contextBuildP95Ms .
                                 ,(plist-get benchmark
                                             :context-build-p95-ms))
              (heapDeltaBytes .
                              ,(plist-get benchmark :heap-delta-bytes)))
            metadata))))
    (when (called-interactively-p 'interactive)
      (message "Final acceptance %s: %s"
               (chat-eval-result-status result)
               (chat-eval-result-id result)))
    result))

(provide 'chat-coding-acceptance)
;;; chat-coding-acceptance.el ends here
