;;; chat-coding-acceptance.el --- Final coding acceptance -*- lexical-binding: t; -*-

;; Copyright (C) 2026 chat.el contributors
;; License: 1PL (One Public License) - https://license.pub/1pl/

;;; Commentary:

;; Strict M19 acceptance aggregation and a reproducible repository benchmark.
;; Source Eval records, lifecycle facts, and repo maps remain authoritative.

;;; Code:

(require 'cl-lib)
(require 'json)
(require 'seq)
(require 'subr-x)
(require 'chat-eval)
(require 'chat-repo-map)
(require 'chat-context-code)
(require 'chat-code)

(defgroup chat-coding-acceptance nil
  "Final coding capability acceptance."
  :group 'chat)

(defconst chat-coding-acceptance--repository-root
  (file-name-as-directory
   (file-truename
    (expand-file-name "../.." (file-name-directory load-file-name))))
  "Repository root captured when the acceptance library is loaded.")

(defconst chat-coding-acceptance--request-footprint-baseline-path
  (expand-file-name
   "tests/fixtures/coding-eval/request-footprint-baseline.json"
   chat-coding-acceptance--repository-root)
  "Committed first-request baseline used to validate measured records.")

(defcustom chat-coding-acceptance-query-repetitions 30
  "Warm query and context-build repetitions in the performance benchmark."
  :type 'integer :group 'chat-coding-acceptance)

(defcustom chat-coding-acceptance-file-count 10000
  "Source files generated by the standalone performance benchmark."
  :type 'integer :group 'chat-coding-acceptance)

(defconst chat-coding-acceptance-failure-kinds
  '(model-ability context-omission tool-error verification-error
                  permission-block infrastructure)
  "Closed failure taxonomy for coding trials.")

(defconst chat-coding-acceptance-reliability-scenarios
  '((goalContinuityRate
     chat-goal-plan-notes-survive-two-compactions-and-restart)
    (goalCompletionEvidenceRate
     chat-goal-progress-requires-known-scoped-evidence
     chat-goal-completion-is-deterministic-and-evidence-backed)
    (goalInvalidTransitionCount
     chat-goal-refuses-incomplete-contracts
     chat-goal-pause-block-resume-and-stale-revision)
    (goalScopeLeakCount
     chat-goal-project-scope-fails-closed-without-content-leakage)
    (planUnauthorizedMutationCount
     chat-plan-mode-tool-boundary-allows-read-and-refuses-effects
     chat-plan-mode-allows-only-dedicated-planning-state-tools)
    (planNonUserApprovalCount
     chat-capability-agent-can-enter-but-not-approve-plan-mode
     chat-plan-mode-submit-requires-complete-plan-and-user-approval)
    (planTransitionConsistencyRate
     chat-plan-mode-persists-read-only-state-across-reload
     chat-plan-mode-submit-requires-complete-plan-and-user-approval
     chat-plan-mode-approval-refuses-a-changed-submitted-plan
     chat-plan-mode-rejection-feedback-returns-to-research
     chat-plan-mode-rejects-invalid-plan-and-stale-transitions)
    (planReadyImplicitExecutionCount
     chat-plan-mode-persists-read-only-state-across-reload))
  "Exact directed scenarios required by the reliability evidence contract.")

(defconst chat-coding-acceptance-reliability-projection-scenario
  'chat-goal-projection-is-protected-bounded-and-state-aware
  "Directed scenario required beside the Goal projection samples.")

(defconst chat-coding-acceptance-quality-languages
  '("python" "javascript" "typescript" "emacs-lisp" "go" "rust"
    "zig" "clojure" "java" "c" "cpp" "sql")
  "Languages required in the deterministic semantic corpus.")

(defconst chat-coding-acceptance-quality-scenarios
  '((semanticCorpusCoverage "semantic-corpus-coverage"
     chat-code-intelligence-index-fixture-meets-definition-and-reference-targets
     chat-code-intelligence-five-language-adversarial-corpus-is-searchable
     chat-repo-map-fixed-queries-exceed-top-five-hit-target)
    (editingSafety "editing-safety"
     chat-files-safe-path-rejects-symlink-escaping-allowed-root
     chat-files-read-set-rejects-existing-write-without-read
     chat-files-read-set-rejects-external-edit-after-read
     chat-files-read-set-rejects-modified-visiting-buffer
     chat-files-read-set-new-file-and-competing-creation
     chat-files-read-set-keeps-multi-file-patch-atomic-on-drift
     chat-files-read-set-revalidates-multi-file-patch-at-commit
     chat-checkpoint-owned-rollback-preserves-preexisting-dirty-work
     chat-checkpoint-external-drift-refuses-before-overwrite)
    (verificationClosure "verification-closure"
     chat-code-verify-detects-manifest-commands-deterministically
     chat-code-verify-unrecognized-project-is-not-run
     chat-code-verify-runtime-evidence-correlates-task-execution-and-wire
     chat-code-verify-required-failures-never-pass
     chat-code-verify-classifies-runtime-terminal-states
     chat-code-verify-repair-passes-after-one-new-diff
     chat-code-verify-repair-stops-on-identical-failure
     chat-code-verify-repair-rejects-unrelated-files)
    (isolationResource "isolation-and-cleanup"
     chat-execution-isolation-inspect-blocks-outside-read-and-all-write
     chat-execution-isolation-build-allows-project-write-and-blocks-escapes
     chat-execution-isolation-filters-environment-and-denies-network
     chat-execution-isolation-timeout-kills-the-whole-process-group
     chat-execution-isolation-cancel-kills-the-whole-process-group
     chat-execution-isolation-restricted-policy-never-falls-back-local
     chat-execution-isolation-start-preparation-failure-cleans-temp-root)
    (agentsScope "agents-scope"
     chat-project-instruction-graph-keeps-directory-scopes
     chat-project-instruction-graph-loads-explicit-dependencies
     chat-project-instruction-dependency-inherits-declaring-scope
     chat-project-instruction-graph-refuses-escape-and-diagnoses-cycle
     chat-project-two-directories-do-not-share-an-answer
     chat-work-context-scope-isolates-directory-and-session)
    (contextContinuity "context-continuity"
     chat-work-note-revision-conflict-preserves-durable-bytes
     chat-work-note-fragments-never-gain-instruction-authority
     chat-work-plan-persists-and-reloads-with-task-scope
     chat-work-plan-restart-blocks-and-explicit-resume-recovers)
    (planAdherence "plan-before-mutation"
     chat-work-plan-gate-covers-mutations-and-consumes-skip-once
     chat-agent-plan-gate-refuses-write-before-tool-execution)
    (planEvidence "plan-evidence"
     chat-work-plan-completion-requires-resolvable-evidence
     chat-work-plan-rejects-evidence-from-another-session-or-task
     chat-work-plan-resolves-tool-events-by-agent-task-scope)
    (planUiStability "plan-ui-stability"
     chat-work-shelf-thousand-updates-preserve-input-and-window)
    (reviewReadOnly "review-read-only"
     chat-code-review-profile-has-zero-write-effects)
    (collaborationConflicts "collaboration-conflicts"
     chat-code-collaboration-conflict-never-overwrites-parent
     chat-code-collaboration-stale-base-is-conflicted
     chat-code-collaboration-post-completion-drift-is-conflicted)
    (postMergeVerification "post-merge-verification"
     chat-code-collaboration-nonconflicting-children-merge-and-verify))
  "Exact directed scenarios required by the non-live quality contract.")

(cl-defstruct (chat-coding-acceptance-gate
               (:constructor chat-coding-acceptance-gate-create))
  name status expected actual evidence)

(defun chat-coding-acceptance--metadata (result)
  "Return executor metadata from coding RESULT."
  (alist-get 'executor (chat-eval-result-metadata result)))

(defun chat-coding-acceptance--number (key data)
  "Return numeric KEY from alist DATA, defaulting to zero."
  (let ((value (alist-get key data)))
    (if (numberp value) value 0)))

(defun chat-coding-acceptance--field (data key)
  "Read KEY from JSON alist, JSON array, or keyword plist DATA."
  (when (vectorp data)
    (setq data (append data nil)))
  (when (listp data)
    (let* ((name (symbol-name key))
           (keyword (intern (concat ":" name)))
           (json-key (concat ":" name)))
      (or (alist-get key data)
          (plist-get data keyword)
          (cl-loop for (candidate value) on data by #'cddr
                   when (and (stringp candidate)
                             (member candidate (list name json-key)))
                   return value)))))

(defconst chat-coding-acceptance--capability-identity-fields
  '(stream tools toolChoice reasoning structuredOutput contextWindow
           maxOutputTokens)
  "Stable model capability fields shared by campaign schema versions.")

(defun chat-coding-acceptance--capability-identity (executor)
  "Return the stable comparison capability identity from EXECUTOR metadata.

Raw snapshots remain immutable evidence.  Comparison selects only model-facing
fields shared by every accepted campaign schema, excluding serializer version,
provenance and implementation features that are part of the revision under
test rather than the frozen provider/model identity."
  (let ((snapshot
         (chat-coding-acceptance--field executor 'modelCapabilitySnapshot)))
    (when (listp snapshot)
      (mapcar
       (lambda (field)
         (cons field (chat-coding-acceptance--field snapshot field)))
       chat-coding-acceptance--capability-identity-fields))))

(defun chat-coding-acceptance--live-request-identity-valid-p (result)
  "Return non-nil when live RESULT has complete observed request identity."
  (let* ((metadata (chat-eval-result-metadata result))
         (campaign-id (chat-coding-acceptance--field metadata 'campaignId)))
    (if (not (and (stringp campaign-id) (not (string-empty-p campaign-id))))
        t
      (let* ((executor (chat-coding-acceptance--field metadata 'executor))
             (provider (chat-coding-acceptance--field executor 'provider))
             (model (chat-coding-acceptance--field executor 'model))
             (request-count
              (chat-coding-acceptance--field executor 'requestCount))
             (stored (chat-coding-acceptance--field executor 'requestModels))
             (requests (if (vectorp stored) (append stored nil) stored)))
        (and (stringp provider) (not (string-empty-p provider))
             (stringp model) (not (string-empty-p model))
             (integerp request-count) (> request-count 0)
             (listp requests) (= request-count (length requests))
             (seq-every-p
              (lambda (request)
                (let ((request-id
                       (chat-coding-acceptance--field request 'requestId)))
                  (and (equal provider
                              (chat-coding-acceptance--field request 'provider))
                       (equal model
                              (chat-coding-acceptance--field request 'model))
                       (stringp request-id)
                       (not (string-empty-p request-id)))))
              requests))))))

(defun chat-coding-acceptance-classify-failure (result)
  "Classify failed coding RESULT into one public failure kind."
  (when (not (eq (chat-eval-result-status result) 'passed))
    (let* ((executor (chat-coding-acceptance--metadata result))
           (checks (chat-eval-result-checks result))
           (text
            (downcase
             (mapconcat
              (lambda (check)
                (format "%s %s %s"
                        (chat-eval-check-name check)
                        (chat-eval-check-actual check)
                        (or (chat-eval-check-detail check) "")))
              (seq-remove #'chat-eval-check-passed checks) " "))))
      (cond
       ((not (chat-coding-acceptance--live-request-identity-valid-p result))
        'infrastructure)
       ((or (eq (chat-eval-result-status result) 'blocked)
            (string-match-p "\\(?:permission\\|approval\\|blocked\\|denied\\)" text))
        'permission-block)
       ((> (chat-coding-acceptance--number 'toolErrorCount executor) 0)
        'tool-error)
       ((string-match-p "\\(?:fixture-setup\\|workspace-cleanup\\)" text)
        'infrastructure)
       ((string-match-p "\\(?:judge\\|verification\\|test\\|build\\|lint\\|typecheck\\)" text)
        'verification-error)
       ((string-match-p "\\(?:missing context\\|wrong file\\|not found\\|omitted\\)" text)
        'context-omission)
       (t 'model-ability)))))

(defun chat-coding-acceptance-failure-summary (results)
  "Return deterministic counts by failure kind for RESULTS."
  (mapcar
   (lambda (kind)
     (cons kind
           (cl-count kind results
                     :key #'chat-coding-acceptance-classify-failure)))
   chat-coding-acceptance-failure-kinds))

(defun chat-coding-acceptance-load-result-directory (directory)
  "Load coding Eval results from DIRECTORY in deterministic order."
  (let (results)
    (when (file-directory-p directory)
      (dolist (file (sort (directory-files directory t "\\.json\\'")
                          #'string<))
        (condition-case nil
            (let ((result (chat-eval-load-result file)))
              (when (string-prefix-p
                     "coding/" (chat-eval-result-scenario-id result))
                (push result results)))
          (error nil))))
    (nreverse results)))

(defun chat-coding-acceptance--read-json-file (file)
  "Read JSON alist from FILE, returning nil on invalid input."
  (when (file-regular-p file)
    (condition-case nil
        (let ((json-object-type 'alist)
              (json-array-type 'list)
              (json-key-type 'symbol))
          (json-read-file file))
      (error nil))))

(defun chat-coding-acceptance--campaign-trial-key (result repetitions)
  "Return validated task/repetition key for RESULT within REPETITIONS."
  (let* ((metadata (chat-eval-result-metadata result))
         (executor (chat-coding-acceptance--field metadata 'executor))
         (task-id (chat-coding-acceptance--field metadata 'taskId))
         (repetition
          (or (chat-coding-acceptance--field metadata 'repetition)
              (chat-coding-acceptance--field executor 'repetition))))
    (when (and (stringp task-id) (not (string-empty-p task-id))
               (integerp repetition) (> repetition 0)
               (<= repetition repetitions))
      (cons task-id repetition))))

(defun chat-coding-acceptance--complete-trial-matrix-p
    (results task-count repetitions)
  "Return non-nil for a complete unique RESULT trial matrix."
  (let ((keys (mapcar
               (lambda (result)
                 (chat-coding-acceptance--campaign-trial-key
                  result repetitions))
               results)))
    (and (seq-every-p #'identity keys)
         (= (length keys) (* task-count repetitions))
         (= (length (delete-dups (copy-sequence keys))) (length keys))
         (= (length (delete-dups (mapcar #'car keys))) task-count))))

(defun chat-coding-acceptance--campaign-directory-gate
    (directory results expected-role &optional expected-tasks
               expected-repetitions gate-label)
  "Validate campaign DIRECTORY and RESULTS for EXPECTED-ROLE.

EXPECTED-TASKS and EXPECTED-REPETITIONS default to the core 30-by-5 matrix.
GATE-LABEL distinguishes an independently measured campaign in the result."
  (let* ((descriptor
          (and directory
               (chat-coding-acceptance--read-json-file
                (expand-file-name "campaign.json" directory))))
         (completion
          (and directory
               (chat-coding-acceptance--read-json-file
                (expand-file-name "completion.json" directory))))
         (campaign-id (alist-get 'campaignId descriptor))
         (configuration-digest (alist-get 'configurationDigest descriptor))
         (manifest-digest (alist-get 'manifestDigest descriptor))
         (implementation-revision
          (alist-get 'implementationRevision descriptor))
         (expected (alist-get 'expectedResultCount descriptor))
         (task-count (alist-get 'taskCount descriptor))
         (repetitions (alist-get 'repetitions descriptor))
         (required-tasks (or expected-tasks 30))
         (required-repetitions (or expected-repetitions 5))
         (required-results (* required-tasks required-repetitions))
         (complete-trial-matrix
          (and (integerp task-count) (integerp repetitions)
               (chat-coding-acceptance--complete-trial-matrix-p
                results task-count repetitions)))
         (results-match
          (and results
               (seq-every-p
                (lambda (result)
                  (let ((metadata (chat-eval-result-metadata result)))
                    (and
                     (equal campaign-id
                            (chat-coding-acceptance--field
                             metadata 'campaignId))
                     (equal expected-role
                            (chat-coding-acceptance--field
                             metadata 'campaignRole))
                     (equal configuration-digest
                            (chat-coding-acceptance--field
                             metadata 'campaignConfigurationDigest))
                     (equal manifest-digest
                            (chat-coding-acceptance--field
                             metadata 'campaignManifestDigest))
                     (equal implementation-revision
                            (chat-coding-acceptance--field
                             metadata 'implementationRevision)))))
                results)))
         (passed
          (and descriptor completion
               (= (or (alist-get 'schemaVersion descriptor) 0) 1)
               (= (or (alist-get 'schemaVersion completion) 0) 1)
               (equal expected-role (alist-get 'role descriptor))
               (equal campaign-id (alist-get 'campaignId completion))
               (equal configuration-digest
                      (alist-get 'configurationDigest completion))
               (= (or (alist-get 'taskCount descriptor) 0) required-tasks)
               (= (or (alist-get 'repetitions descriptor) 0)
                  required-repetitions)
               (= (or expected 0) required-results)
               (= (or (alist-get 'expectedResultCount completion) 0)
                  required-results)
               (= (or (alist-get 'resultCount completion) 0)
                  required-results)
               (= (length results) required-results)
               complete-trial-matrix
               results-match
               (eq t (alist-get 'complete completion)))))
    (chat-coding-acceptance-gate-create
     :name (format "live-eval-%s-campaign-record"
                   (or gate-label expected-role))
     :status (cond
              ((null directory) 'blocked)
              (passed 'passed)
              (t 'failed))
     :expected (format "immutable %d-task x %d campaign and complete terminal record"
                       required-tasks required-repetitions)
     :actual
     `((campaignId . ,campaign-id)
       (expectedResults . ,expected)
       (recordedResults . ,(and completion
                                (alist-get 'resultCount completion)))
       (loadedResults . ,(length results))
       (completeTrialMatrix . ,(and complete-trial-matrix t)))
     :evidence
     (unless passed
       "Use a fresh campaign directory and wait for completion.json."))))

(defun chat-coding-acceptance--task-id (result)
  "Return stable task id from coding RESULT."
  (chat-coding-acceptance--field
   (chat-eval-result-metadata result) 'taskId))

(defun chat-coding-acceptance--group-by-task (results)
  "Return task-id table for RESULTS."
  (let ((table (make-hash-table :test 'equal)))
    (dolist (result results table)
      (when-let* ((id (chat-coding-acceptance--task-id result)))
        (puthash id (cons result (gethash id table)) table)))))

(defun chat-coding-acceptance--valid-results (results)
  "Return RESULTS excluding infrastructure-invalid trials."
  (seq-remove
   (lambda (result)
     (or (not (chat-coding-acceptance--live-request-identity-valid-p result))
         (eq (chat-coding-acceptance-classify-failure result) 'infrastructure)))
   results))

(defun chat-coding-acceptance--success-rate (results)
  "Return passed fraction for RESULTS, or nil when empty."
  (when results
    (/ (float (cl-count 'passed results :key #'chat-eval-result-status))
       (length results))))

(defun chat-coding-acceptance--trial-identity (result)
  "Return comparison identity for coding RESULT."
  (let* ((metadata (chat-eval-result-metadata result))
         (executor (chat-coding-acceptance--field metadata 'executor)))
    (list
     (chat-coding-acceptance--task-id result)
     (chat-eval-result-scenario-revision result)
     (chat-eval-result-fixture-digest result)
     (chat-coding-acceptance--field executor 'provider)
     (chat-coding-acceptance--field executor 'model)
     (chat-coding-acceptance--capability-identity executor)
     (chat-coding-acceptance--field executor 'profile)
     (chat-coding-acceptance--field executor 'transport)
     (chat-coding-acceptance--field executor 'approvalMode))))

(defun chat-coding-acceptance--campaign-identity (result)
  "Return the live campaign identity recorded by RESULT."
  (let ((metadata (chat-eval-result-metadata result)))
    (list
     (chat-coding-acceptance--field metadata 'campaignId)
     (chat-coding-acceptance--field metadata 'campaignRole)
     (chat-coding-acceptance--field metadata 'campaignConfigurationDigest)
     (chat-coding-acceptance--field metadata 'campaignManifestDigest)
     (chat-coding-acceptance--field metadata 'implementationRevision))))

(defun chat-coding-acceptance--complete-campaign-identity-p (identity)
  "Return non-nil when every field in campaign IDENTITY is present."
  (seq-every-p
   (lambda (value)
     (and (stringp value) (not (string-empty-p value))))
   identity))

(defun chat-coding-acceptance--campaign-gate (baseline current)
  "Return the campaign isolation gate for BASELINE and CURRENT."
  (let* ((baseline-identities
          (delete-dups
           (mapcar #'chat-coding-acceptance--campaign-identity baseline)))
         (current-identities
          (delete-dups
           (mapcar #'chat-coding-acceptance--campaign-identity current)))
         (left (car baseline-identities))
         (right (car current-identities))
         (passed
          (and (= (length baseline-identities) 1)
               (= (length current-identities) 1)
               (chat-coding-acceptance--complete-campaign-identity-p left)
               (chat-coding-acceptance--complete-campaign-identity-p right)
               (equal (nth 1 left) "baseline")
               (equal (nth 1 right) "current")
               (not (equal (nth 0 left) (nth 0 right)))
               (not (equal (nth 2 left) (nth 2 right)))
               (equal (nth 3 left) (nth 3 right))
               (not (equal (nth 4 left) (nth 4 right))))))
    (chat-coding-acceptance-gate-create
     :name "live-eval-campaign-isolation"
     :status (if passed 'passed 'failed)
     :expected
     "one baseline and one current campaign; same manifest; distinct configurations and revisions"
     :actual `((baseline . ,baseline-identities)
               (current . ,current-identities))
     :evidence
     (unless passed
       "Generate each result set in a fresh isolated live campaign."))))

(defun chat-coding-acceptance--compatible-identities-p (baseline current)
  "Return non-nil when BASELINE and CURRENT have comparable task identities."
  (let ((left (chat-coding-acceptance--group-by-task baseline))
        (right (chat-coding-acceptance--group-by-task current))
        compatible)
    (setq compatible (= (hash-table-count left) (hash-table-count right)))
    (maphash
     (lambda (task trials)
       (let* ((other (gethash task right))
              (left-identities
               (delete-dups
                (mapcar (lambda (trial)
                          (cdr (chat-coding-acceptance--trial-identity trial)))
                        trials)))
              (right-identities
               (and other
                    (delete-dups
                     (mapcar
                      (lambda (trial)
                        (cdr (chat-coding-acceptance--trial-identity trial)))
                      other)))))
         (unless (and (= (length left-identities) 1)
                      (= (length right-identities) 1)
                      (equal (car left-identities)
                             (car right-identities)))
           (setq compatible nil))))
     left)
    compatible))

(defun chat-coding-acceptance--five-by-thirty-p (results)
  "Return non-nil when RESULTS contain exactly five trials for 30 tasks."
  (let ((table (chat-coding-acceptance--group-by-task results))
        (valid t))
    (maphash (lambda (_task trials)
               (unless (= (length trials) 5) (setq valid nil)))
             table)
    (and valid (= (hash-table-count table) 30) (= (length results) 150))))

(defun chat-coding-acceptance--out-of-scope-count (results)
  "Return aggregate out-of-scope edit count for RESULTS."
  (apply
   #'+ 0
   (mapcar
    (lambda (result)
      (length (or (chat-coding-acceptance--field
                   (chat-eval-result-metadata result) 'outOfScopeFiles)
                  nil)))
    results)))

(defun chat-coding-acceptance--unverified-pass-count (results)
  "Return passed trials without a deterministic judge check."
  (cl-count-if
   (lambda (result)
     (and (eq (chat-eval-result-status result) 'passed)
          (null
           (seq-remove
            (lambda (check)
              (member (chat-eval-check-name check)
                      '("executor-status" "allowed-paths" "workspace-cleanup")))
            (chat-eval-result-checks result)))))
   results))

(defun chat-coding-acceptance--usage-input-tokens (result field)
  "Return trusted input tokens from usage FIELD in RESULT, or nil."
  (let* ((executor (chat-coding-acceptance--metadata result))
         (usage (chat-coding-acceptance--field executor field)))
    (or (chat-coding-acceptance--field usage 'input_tokens)
        (chat-coding-acceptance--field usage 'input-tokens)
        (chat-coding-acceptance--field usage 'prompt_tokens))))

(defun chat-coding-acceptance--first-request-input-tokens (result)
  "Return trusted first-request input tokens from RESULT, or nil."
  (chat-coding-acceptance--usage-input-tokens
   result 'firstRequestTokenUsage))

(defun chat-coding-acceptance--task-tags (result)
  "Return normalized task tags from RESULT."
  (mapcar (lambda (tag) (downcase (format "%s" tag)))
          (or (chat-coding-acceptance--field
               (chat-eval-result-metadata result) 'taskTags)
              nil)))

(defun chat-coding-acceptance--fixture-indexed-file-count (result)
  "Return trusted indexed fixture-file count from RESULT."
  (let ((value (chat-coding-acceptance--field
                (chat-eval-result-metadata result)
                'fixtureIndexedFileCount)))
    (and (integerp value) value)))

(defun chat-coding-acceptance--large-repo-token-gate (baseline current)
  "Return the large-repository token gate for BASELINE and CURRENT."
  (let* ((baseline-large
          (seq-filter
           (lambda (result)
             (member "large-repo"
                     (chat-coding-acceptance--task-tags result)))
           (chat-coding-acceptance--valid-results baseline)))
         (current-large
          (seq-filter
           (lambda (result)
             (member "large-repo"
                     (chat-coding-acceptance--task-tags result)))
           (chat-coding-acceptance--valid-results current)))
         (baseline-usage
          (delq nil (mapcar #'chat-coding-acceptance--first-request-input-tokens
                            baseline-large)))
         (current-usage
          (delq nil (mapcar #'chat-coding-acceptance--first-request-input-tokens
                            current-large)))
         (invalid-fixtures
          (seq-remove
           (lambda (result)
             (let ((count
                    (chat-coding-acceptance--fixture-indexed-file-count
                     result)))
               (and count (>= count 10000))))
           (append baseline-large current-large)))
         (complete
          (and baseline-large current-large
               (null invalid-fixtures)
               (= (length baseline-large) (length baseline-usage))
               (= (length current-large) (length current-usage))
               (seq-every-p (lambda (value)
                              (and (numberp value) (> value 0)))
                            (append baseline-usage current-usage))))
         (baseline-median
          (and complete (chat-coding-acceptance--median baseline-usage)))
         (current-median
          (and complete (chat-coding-acceptance--median current-usage))))
    (chat-coding-acceptance-gate-create
     :name "live-eval-large-repo-token-budget"
     :status
     (cond
      (invalid-fixtures 'failed)
      ((not complete) 'blocked)
      ((<= current-median (* 0.85 baseline-median)) 'passed)
      (t 'failed))
     :expected "large-repo median first-request input tokens reduced >=15%"
     :actual
     (cond
      (invalid-fixtures
       (format "invalid indexed fixture samples=%d"
               (length invalid-fixtures)))
      (complete
       (format "baseline=%s current=%s" baseline-median current-median))
      (t
       (format "baseline=%d/%d current=%d/%d usage samples"
               (length baseline-usage) (length baseline-large)
               (length current-usage) (length current-large))))
     :evidence
     (cond
      (invalid-fixtures
       "Large-repo trials must record at least 10,000 indexed fixture files.")
      ((not complete)
       "Add fixed large-repo tagged trials with trusted usage for both configurations.")))))

(defun chat-coding-acceptance--large-repo-results (results)
  "Return valid large-repository RESULTS."
  (seq-filter
   (lambda (result)
     (member "large-repo" (chat-coding-acceptance--task-tags result)))
   (chat-coding-acceptance--valid-results results)))

(defun chat-coding-acceptance--single-campaign-revision (results)
  "Return the one implementation revision in RESULTS, or nil."
  (let ((revisions
         (delete-dups
          (mapcar
           (lambda (result)
             (chat-coding-acceptance--field
              (chat-eval-result-metadata result) 'implementationRevision))
           results))))
    (and (= (length revisions) 1)
         (stringp (car revisions))
         (not (string-empty-p (car revisions)))
         (car revisions))))

(defun chat-coding-acceptance--large-repo-evidence-gate
    (baseline current performance-baseline performance-current)
  "Validate dedicated large-repository evidence against the core campaigns."
  (let* ((core-baseline (chat-coding-acceptance--large-repo-results baseline))
         (core-current (chat-coding-acceptance--large-repo-results current))
         (measured-baseline
          (chat-coding-acceptance--large-repo-results performance-baseline))
         (measured-current
          (chat-coding-acceptance--large-repo-results performance-current))
         (core-baseline-revision
          (chat-coding-acceptance--single-campaign-revision baseline))
         (core-current-revision
          (chat-coding-acceptance--single-campaign-revision current))
         (measured-baseline-revision
          (chat-coding-acceptance--single-campaign-revision
           performance-baseline))
         (measured-current-revision
          (chat-coding-acceptance--single-campaign-revision
           performance-current))
         (passed
          (and (= (length measured-baseline) 5)
               (= (length measured-current) 5)
               (= (hash-table-count
                   (chat-coding-acceptance--group-by-task measured-baseline))
                  1)
               (= (hash-table-count
                   (chat-coding-acceptance--group-by-task measured-current))
                  1)
               (chat-coding-acceptance--compatible-identities-p
                measured-baseline measured-current)
               (chat-coding-acceptance--compatible-identities-p
                core-baseline measured-baseline)
               (chat-coding-acceptance--compatible-identities-p
                core-current measured-current)
               core-baseline-revision core-current-revision
               measured-baseline-revision measured-current-revision
               (equal core-baseline-revision measured-baseline-revision)
               (equal core-current-revision measured-current-revision)
               (eq 'passed
                   (chat-coding-acceptance-gate-status
                    (chat-coding-acceptance--campaign-gate
                     performance-baseline performance-current))))))
    (chat-coding-acceptance-gate-create
     :name "live-eval-large-repo-evidence"
     :status (cond
              ((or (null performance-baseline) (null performance-current))
               'blocked)
              (passed 'passed)
              (t 'failed))
     :expected
     "dedicated 1-task x 5 pair matching core task, model, capability, and revisions"
     :actual
     `((baselineSamples . ,(length measured-baseline))
       (currentSamples . ,(length measured-current))
       (baselineRevision .
                         ,measured-baseline-revision)
       (currentRevision .
                        ,measured-current-revision))
     :evidence
     (unless passed
       "Run the fixed large-repo manifest five times for both exact implementations."))))

(defun chat-coding-acceptance--median (values)
  "Return median of numeric VALUES."
  (when values
    (let* ((ordered (sort (copy-sequence values) #'<))
           (count (length ordered))
           (middle (/ count 2)))
      (if (cl-oddp count)
          (nth middle ordered)
        (/ (+ (nth (1- middle) ordered) (nth middle ordered)) 2.0)))))

(defun chat-coding-acceptance-live-gates
    (baseline current performance-baseline performance-current)
  "Return final live-Eval gates for core and dedicated performance campaigns."
  (if (or (null baseline) (null current))
      (list
       (chat-coding-acceptance-gate-create
        :name "live-eval-comparison" :status 'blocked
        :expected "M9 and M19 result sets"
        :actual "missing"
        :evidence "Run 30 tasks five times for both comparable configurations.")
       (chat-coding-acceptance--large-repo-evidence-gate
        baseline current performance-baseline performance-current)
       (chat-coding-acceptance--large-repo-token-gate
        performance-baseline performance-current))
    (let* ((baseline-valid (chat-coding-acceptance--valid-results baseline))
           (current-valid (chat-coding-acceptance--valid-results current))
           (baseline-rate
            (chat-coding-acceptance--success-rate baseline-valid))
           (current-rate
            (chat-coding-acceptance--success-rate current-valid))
           (usage
            (delq nil
                  (mapcar #'chat-coding-acceptance--first-request-input-tokens
                          current-valid)))
           (baseline-usage
            (delq nil
                  (mapcar #'chat-coding-acceptance--first-request-input-tokens
                          baseline-valid)))
           (missing-usage
            (if current-valid
                (- 1.0 (/ (float (length usage)) (length current-valid)))
              1.0))
           (baseline-missing-usage
            (if baseline-valid
                (- 1.0
                   (/ (float (length baseline-usage))
                      (length baseline-valid)))
              1.0)))
      (list
       (chat-coding-acceptance-gate-create
        :name "live-eval-sample"
        :status (if (and
                     (chat-coding-acceptance--five-by-thirty-p baseline-valid)
                     (chat-coding-acceptance--five-by-thirty-p current-valid))
                    'passed 'failed)
        :expected "30 tasks x 5 for baseline and current"
        :actual (format "raw=%d/%d valid=%d/%d"
                        (length baseline) (length current)
                        (length baseline-valid) (length current-valid)))
       (chat-coding-acceptance--campaign-gate baseline current)
       (chat-coding-acceptance-gate-create
        :name "live-eval-identity"
        :status (if (chat-coding-acceptance--compatible-identities-p
                     baseline current) 'passed 'failed)
        :expected "same task revision, fixture, model, and stable capability identity"
        :actual "compared")
       (chat-coding-acceptance-gate-create
        :name "live-eval-success-floor"
        :status (if (and current-rate (>= current-rate 0.80)) 'passed 'failed)
        :expected ">=80%" :actual current-rate)
       (chat-coding-acceptance-gate-create
        :name "live-eval-no-regression"
        :status (if (and baseline-rate current-rate
                         (>= current-rate baseline-rate)) 'passed 'failed)
        :expected baseline-rate :actual current-rate)
       (chat-coding-acceptance-gate-create
        :name "live-eval-target-or-improvement"
        :status (if (and baseline-rate current-rate
                         (or (>= current-rate 0.90)
                             (>= (- current-rate baseline-rate) 0.15)))
                    'passed 'failed)
        :expected ">=90% or +15 percentage points" :actual current-rate)
       (chat-coding-acceptance-gate-create
        :name "live-eval-scope"
        :status (if (zerop (chat-coding-acceptance--out-of-scope-count current))
                    'passed 'failed)
        :expected 0 :actual (chat-coding-acceptance--out-of-scope-count current))
       (chat-coding-acceptance-gate-create
        :name "live-eval-verification-evidence"
        :status (if (zerop (chat-coding-acceptance--unverified-pass-count current))
                    'passed 'failed)
        :expected 0 :actual (chat-coding-acceptance--unverified-pass-count current))
       (chat-coding-acceptance-gate-create
        :name "live-eval-first-request-token-coverage"
        :status (if (and (<= baseline-missing-usage 0.05)
                         (<= missing-usage 0.05))
                    'passed 'blocked)
        :expected "missing <=5% in baseline and current"
        :actual `((baseline . ,baseline-missing-usage)
                  (current . ,missing-usage)))
       (chat-coding-acceptance-gate-create
        :name "live-eval-first-request-input-token-budget"
        :status
        (if (and baseline-usage usage
                 (<= baseline-missing-usage 0.05)
                 (<= missing-usage 0.05))
            (if (<= (chat-coding-acceptance--median usage)
                    (* 1.10 (chat-coding-acceptance--median baseline-usage)))
                'passed 'failed)
          'blocked)
        :expected "current first-request median <=110% of baseline"
        :actual
        `((baseline . ,(chat-coding-acceptance--median baseline-usage))
          (current . ,(chat-coding-acceptance--median usage))))
       (chat-coding-acceptance--large-repo-evidence-gate
        baseline current performance-baseline performance-current)
       (chat-coding-acceptance--large-repo-token-gate
        performance-baseline performance-current)))))

(defun chat-coding-acceptance--reliability-gate
    (name expected actual valid-p passed-p &optional evidence)
  "Return a strict reliability gate for NAME.

VALID-P distinguishes absent or malformed evidence from a measured failure.
PASSED-P is considered only when VALID-P is non-nil."
  (chat-coding-acceptance-gate-create
   :name name
   :status (cond ((not valid-p) 'blocked)
                 (passed-p 'passed)
                 (t 'failed))
   :expected expected
   :actual actual
   :evidence (unless valid-p evidence)))

(defun chat-coding-acceptance-reliability-gates (metadata)
  "Return Goal and Plan Mode gates from bounded acceptance METADATA.

The evidence contract lives under `runtimeReliability'.  Missing or malformed
measurements block final acceptance; measured values outside the exact limits
fail it."
  (let* ((facts (chat-coding-acceptance--field metadata 'runtimeReliability))
         (goal-continuity
          (chat-coding-acceptance--field facts 'goalContinuityRate))
         (goal-completion
          (chat-coding-acceptance--field facts 'goalCompletionEvidenceRate))
         (goal-invalid
          (chat-coding-acceptance--field facts 'goalInvalidTransitionCount))
         (goal-leaks
          (chat-coding-acceptance--field facts 'goalScopeLeakCount))
         (goal-prompt
          (chat-coding-acceptance--field facts 'goalProjectionMedianRatio))
         (plan-mutations
          (chat-coding-acceptance--field facts 'planUnauthorizedMutationCount))
         (plan-approvals
          (chat-coding-acceptance--field facts 'planNonUserApprovalCount))
         (plan-consistency
          (chat-coding-acceptance--field facts 'planTransitionConsistencyRate))
         (plan-implicit
          (chat-coding-acceptance--field facts 'planReadyImplicitExecutionCount))
         (rate-p (lambda (value)
                   (and (numberp value) (<= 0.0 value) (<= value 1.0))))
         (count-p (lambda (value)
                    (and (integerp value) (>= value 0)))))
    (list
     (chat-coding-acceptance--reliability-gate
      "goal-continuity" "100%" goal-continuity
      (funcall rate-p goal-continuity)
      (and (numberp goal-continuity) (= goal-continuity 1.0))
      "Measure one Goal across 20 turns, two compactions, reload, and restart.")
     (chat-coding-acceptance--reliability-gate
      "goal-completion-evidence" "100%" goal-completion
      (funcall rate-p goal-completion)
      (and (numberp goal-completion) (= goal-completion 1.0))
      "Measure required criteria, stopping predicate, and scoped evidence resolution.")
     (chat-coding-acceptance--reliability-gate
      "goal-invalid-transitions" 0 goal-invalid
      (funcall count-p goal-invalid) (equal goal-invalid 0)
      "Count illegal completion, paused auto-advance, and Agent resume attempts.")
     (chat-coding-acceptance--reliability-gate
      "goal-scope-leaks" 0 goal-leaks
      (funcall count-p goal-leaks) (equal goal-leaks 0)
      "Count Goal content disclosed outside its canonical project scope.")
     (chat-coding-acceptance--reliability-gate
      "goal-projection-token-budget" "median <=3%" goal-prompt
      (funcall rate-p goal-prompt)
      (and (numberp goal-prompt) (<= goal-prompt 0.03))
      "Record the median Goal projection/input-token ratio.")
     (chat-coding-acceptance--reliability-gate
      "plan-mode-unauthorized-mutations" 0 plan-mutations
      (funcall count-p plan-mutations) (equal plan-mutations 0)
      "Count successful source, shell, child, repair, merge, permission, and unknown effects.")
     (chat-coding-acceptance--reliability-gate
      "plan-mode-non-user-approvals" 0 plan-approvals
      (funcall count-p plan-approvals) (equal plan-approvals 0)
      "Count approvals accepted from any source other than the user path.")
     (chat-coding-acceptance--reliability-gate
      "plan-mode-transition-consistency" "100%" plan-consistency
      (funcall rate-p plan-consistency)
      (and (numberp plan-consistency) (= plan-consistency 1.0))
      "Measure submit, reject, approve, restore, and plan identity consistency.")
     (chat-coding-acceptance--reliability-gate
      "plan-mode-ready-implicit-execution" 0 plan-implicit
      (funcall count-p plan-implicit) (equal plan-implicit 0)
     "Count executions triggered merely by restoring a ready plan."))))

(defun chat-coding-acceptance--sequence-list (value)
  "Return proper list represented by sequence VALUE, or nil."
  (cond
   ((vectorp value) (append value nil))
   ((proper-list-p value) value)))

(defun chat-coding-acceptance--passing-status-p (value)
  "Return non-nil when VALUE represents a passed status."
  (or (eq value 'passed) (equal value "passed")))

(defun chat-coding-acceptance--reliability-gate-records-valid-p (metadata)
  "Return non-nil when METADATA carries the exact recomputed gate records."
  (let ((records
         (chat-coding-acceptance--sequence-list
          (chat-coding-acceptance--field metadata 'acceptanceGates)))
        (gates (chat-coding-acceptance-reliability-gates metadata)))
    (and (= (length records) (length gates))
         (cl-every
          (lambda (pair)
            (let ((record (car pair)) (gate (cdr pair)))
              (and
               (equal (chat-coding-acceptance--field record 'name)
                      (chat-coding-acceptance-gate-name gate))
               (chat-coding-acceptance--passing-status-p
                (chat-coding-acceptance--field record 'status))
               (eq 'passed (chat-coding-acceptance-gate-status gate))
               (equal (chat-coding-acceptance--field record 'expected)
                      (chat-coding-acceptance-gate-expected gate))
               (equal (chat-coding-acceptance--field record 'actual)
                      (chat-coding-acceptance-gate-actual gate)))))
          (cl-mapcar #'cons records gates)))))

(defun chat-coding-acceptance--reliability-tests-valid-p
    (records expected)
  "Return non-nil when RECORDS exactly prove EXPECTED test names."
  (let ((items (chat-coding-acceptance--sequence-list records)))
    (and (= (length items) (length expected))
         (cl-every
          (lambda (pair)
            (let ((record (car pair)) (test (cdr pair)))
              (and
               (equal (chat-coding-acceptance--field record 'test)
                      (symbol-name test))
               (eq t (chat-coding-acceptance--field record 'passed)))))
          (cl-mapcar #'cons items expected)))))

(defun chat-coding-acceptance--reliability-samples-valid-p
    (samples expected-median)
  "Return non-nil when SAMPLES are the complete measured projection series."
  (let ((items (chat-coding-acceptance--sequence-list samples)))
    (and (= (length items) 20)
         (equal (mapcar (lambda (sample)
                          (chat-coding-acceptance--field sample 'turn))
                        items)
                (number-sequence 1 20))
         (cl-every
          (lambda (sample)
            (let ((goal (chat-coding-acceptance--field sample 'goalTokens))
                  (input (chat-coding-acceptance--field sample 'inputTokens))
                  (ratio (chat-coding-acceptance--field sample 'ratio)))
              (and (numberp goal) (> goal 0)
                   (numberp input) (> input 0)
                   (numberp ratio) (<= 0.0 ratio) (<= ratio 1.0)
                   (<= (abs (- ratio (/ (float goal) input))) 1e-9))))
          items)
         (numberp expected-median)
         (<= (abs
              (- expected-median
                 (chat-coding-acceptance--median
                  (mapcar
                   (lambda (sample)
                     (chat-coding-acceptance--field sample 'ratio))
                   items))))
             1e-9))))

(defun chat-coding-acceptance--reliability-evidence-valid-p (metadata)
  "Return non-nil when METADATA contains every directed evidence record."
  (let* ((evidence (chat-coding-acceptance--field metadata 'evidence))
         (projection
          (chat-coding-acceptance--field
           evidence 'goalProjectionMedianRatio))
         (facts (chat-coding-acceptance--field metadata 'runtimeReliability)))
    (and
     (cl-every
      (lambda (group)
        (chat-coding-acceptance--reliability-tests-valid-p
         (chat-coding-acceptance--field evidence (car group))
         (cdr group)))
      chat-coding-acceptance-reliability-scenarios)
     (chat-coding-acceptance--reliability-tests-valid-p
      (chat-coding-acceptance--field projection 'tests)
      (list chat-coding-acceptance-reliability-projection-scenario))
     (chat-coding-acceptance--reliability-samples-valid-p
      (chat-coding-acceptance--field projection 'samples)
      (chat-coding-acceptance--field facts 'goalProjectionMedianRatio)))))

(defun chat-coding-acceptance-reliability-record-gate
    (metadata expected-revision)
  "Validate complete reliability METADATA for EXPECTED-REVISION."
  (let* ((schema (chat-coding-acceptance--field metadata 'schemaVersion))
         (revision
          (chat-coding-acceptance--field metadata 'implementationRevision))
         (tree-clean
          (chat-coding-acceptance--field metadata 'implementationTreeClean))
         (measured-at (chat-coding-acceptance--field metadata 'measuredAt))
         (records
          (chat-coding-acceptance--sequence-list
           (chat-coding-acceptance--field metadata 'acceptanceGates)))
         (projection
          (chat-coding-acceptance--field
           (chat-coding-acceptance--field metadata 'evidence)
           'goalProjectionMedianRatio))
         (samples
          (chat-coding-acceptance--sequence-list
           (chat-coding-acceptance--field projection 'samples)))
         (valid
          (and (= (or schema 0) 1)
               (stringp expected-revision)
               (not (string-empty-p expected-revision))
               (equal revision expected-revision)
               (eq t tree-clean)
               (stringp measured-at)
               (not (string-empty-p measured-at))
               (chat-coding-acceptance--reliability-gate-records-valid-p
                metadata)
               (chat-coding-acceptance--reliability-evidence-valid-p
                metadata))))
    (chat-coding-acceptance-gate-create
     :name "runtime-reliability-record"
     :status (if valid 'passed 'blocked)
     :expected "clean complete measured record for current implementation"
     :actual `((implementationRevision . ,revision)
               (expectedRevision . ,expected-revision)
               (treeClean . ,tree-clean)
               (gateCount . ,(length records))
               (projectionSampleCount . ,(length samples)))
     :evidence
     (unless valid
       "Load the complete clean reliability JSON for the current campaign revision."))))

(defun chat-coding-acceptance--ratio (numerator denominator)
  "Return NUMERATOR divided by DENOMINATOR, or nil for invalid counts."
  (when (and (integerp numerator) (>= numerator 0)
             (integerp denominator) (> denominator 0)
             (<= numerator denominator))
    (/ (float numerator) denominator)))

(defun chat-coding-acceptance--semantic-row-summary (row)
  "Return recomputed semantic metrics for one raw corpus ROW."
  (let* ((definition-expected
          (chat-coding-acceptance--field row 'definitionExpected))
         (definition-hits
          (chat-coding-acceptance--field row 'definitionHits))
         (reference-expected
          (chat-coding-acceptance--field row 'referenceExpected))
         (reference-returned
          (chat-coding-acceptance--field row 'referenceReturned))
         (reference-true
          (chat-coding-acceptance--field row 'referenceTrue))
         (top-five-queries
          (chat-coding-acceptance--field row 'topFiveQueries))
         (top-five-hits
          (chat-coding-acceptance--field row 'topFiveHits))
         (definition
          (chat-coding-acceptance--ratio definition-hits definition-expected))
         (precision
          (chat-coding-acceptance--ratio reference-true reference-returned))
         (recall
          (chat-coding-acceptance--ratio reference-true reference-expected))
         (top-five
          (chat-coding-acceptance--ratio top-five-hits top-five-queries)))
    (when (and definition precision recall top-five)
      `((definitionAccuracy . ,definition)
        (referencePrecision . ,precision)
        (referenceRecall . ,recall)
        (topFiveHitRate . ,top-five)))))

(defun chat-coding-acceptance--semantic-summary (corpus)
  "Recompute overall and per-language semantic metrics from CORPUS."
  (let ((rows (chat-coding-acceptance--sequence-list corpus)))
    (when (and
           (= (length rows) (length chat-coding-acceptance-quality-languages))
           (equal
            (mapcar (lambda (row)
                      (chat-coding-acceptance--field row 'language))
                    rows)
            chat-coding-acceptance-quality-languages)
           (cl-every #'chat-coding-acceptance--semantic-row-summary rows))
      (let* ((sum
              (lambda (field)
                (apply #'+
                       (mapcar
                        (lambda (row)
                          (chat-coding-acceptance--field row field))
                        rows))))
             (overall-row
              `((definitionExpected . ,(funcall sum 'definitionExpected))
                (definitionHits . ,(funcall sum 'definitionHits))
                (referenceExpected . ,(funcall sum 'referenceExpected))
                (referenceReturned . ,(funcall sum 'referenceReturned))
                (referenceTrue . ,(funcall sum 'referenceTrue))
                (topFiveQueries . ,(funcall sum 'topFiveQueries))
                (topFiveHits . ,(funcall sum 'topFiveHits))))
             (overall
              (chat-coding-acceptance--semantic-row-summary overall-row))
             (by-language
              (mapcar
               (lambda (row)
                 (cons
                  (cons 'language
                        (chat-coding-acceptance--field row 'language))
                  (chat-coding-acceptance--semantic-row-summary row)))
               rows)))
        `((overall . ,overall) (byLanguage . ,(vconcat by-language)))))))

(defun chat-coding-acceptance--string-set (value)
  "Return VALUE as a unique nonempty string list, or nil."
  (let ((items (chat-coding-acceptance--sequence-list value)))
    (when (and items
               (cl-every (lambda (item)
                           (and (stringp item) (not (string-empty-p item))))
                         items)
               (= (length items)
                  (length (delete-dups (copy-sequence items)))))
      items)))

(defun chat-coding-acceptance--review-summary (corpus)
  "Recompute Review precision and recall from raw CORPUS sets."
  (let* ((expected
          (chat-coding-acceptance--string-set
           (chat-coding-acceptance--field corpus 'expectedCriticalHigh)))
         (reported
          (chat-coding-acceptance--string-set
           (chat-coding-acceptance--field corpus 'reportedFormal)))
         (confirmed (and expected reported
                         (seq-intersection reported expected #'equal))))
    (when (and expected reported)
      `((recall . ,(/ (float (length confirmed)) (length expected)))
        (precision . ,(/ (float (length confirmed)) (length reported)))
        (expectedCount . ,(length expected))
        (reportedCount . ,(length reported))
        (confirmedCount . ,(length confirmed))))))

(defun chat-coding-acceptance--plan-note-samples-median (samples)
  "Validate SAMPLES and return their plan plus work-note token median."
  (let ((items (chat-coding-acceptance--sequence-list samples)))
    (when (and
           (= (length items) 20)
           (equal
            (mapcar (lambda (sample)
                      (chat-coding-acceptance--field sample 'turn))
                    items)
            (number-sequence 1 20))
           (cl-every
            (lambda (sample)
              (let ((plan (chat-coding-acceptance--field sample 'planTokens))
                    (note (chat-coding-acceptance--field
                           sample 'workNoteTokens))
                    (input (chat-coding-acceptance--field sample 'inputTokens))
                    (ratio (chat-coding-acceptance--field sample 'ratio)))
                (and (integerp plan) (> plan 0)
                     (integerp note) (> note 0)
                     (numberp input) (> input 0)
                     (numberp ratio) (<= 0.0 ratio) (<= ratio 1.0)
                     (<= (abs (- ratio (/ (float (+ plan note)) input)))
                         1e-9))))
            items))
      (chat-coding-acceptance--median
       (mapcar (lambda (sample)
                 (chat-coding-acceptance--field sample 'ratio))
               items)))))

(defun chat-coding-acceptance--metric-valid-p (value)
  "Return non-nil when VALUE is a normalized rate."
  (and (numberp value) (<= 0.0 value) (<= value 1.0)))

(defun chat-coding-acceptance--quality-test-records-shape-p
    (records expected)
  "Return non-nil when RECORDS exactly describe EXPECTED tests."
  (let ((items (chat-coding-acceptance--sequence-list records)))
    (and (= (length items) (length expected))
         (cl-every
          (lambda (pair)
            (let ((record (car pair)) (test (cdr pair)))
              (and
               (equal (chat-coding-acceptance--field record 'test)
                      (symbol-name test))
               (assq 'passed record)
               (memq (chat-coding-acceptance--field record 'passed)
                     '(t :json-false)))))
          (cl-mapcar #'cons items expected)))))

(defun chat-coding-acceptance--quality-tests-passed-p (records)
  "Return non-nil when every directed test in RECORDS passed."
  (cl-every
   (lambda (record)
     (eq t (chat-coding-acceptance--field record 'passed)))
   (chat-coding-acceptance--sequence-list records)))

(defun chat-coding-acceptance--quality-language-metrics-valid-p (semantic)
  "Return non-nil when SEMANTIC has every normalized language metric."
  (let* ((overall (chat-coding-acceptance--field semantic 'overall))
         (rows
          (chat-coding-acceptance--sequence-list
           (chat-coding-acceptance--field semantic 'byLanguage)))
         (metrics '(definitionAccuracy referencePrecision
                    referenceRecall topFiveHitRate)))
    (and
     (= (length rows) (length chat-coding-acceptance-quality-languages))
     (equal
      (mapcar (lambda (row)
                (chat-coding-acceptance--field row 'language))
              rows)
     chat-coding-acceptance-quality-languages)
     (cl-every
      (lambda (metric)
        (let ((aggregate (chat-coding-acceptance--field overall metric)))
          (and
           (chat-coding-acceptance--metric-valid-p aggregate)
           (cl-every
            (lambda (row)
              (let ((value (chat-coding-acceptance--field row metric)))
                (chat-coding-acceptance--metric-valid-p value)))
            rows))))
      metrics))))

(defun chat-coding-acceptance--quality-language-spread-p (semantic)
  "Return non-nil when SEMANTIC language metrics stay within ten points."
  (let* ((overall (chat-coding-acceptance--field semantic 'overall))
         (rows
          (chat-coding-acceptance--sequence-list
           (chat-coding-acceptance--field semantic 'byLanguage)))
         (metrics '(definitionAccuracy referencePrecision
                    referenceRecall topFiveHitRate)))
    (and
     (chat-coding-acceptance--quality-language-metrics-valid-p semantic)
     (cl-every
      (lambda (metric)
        (let ((aggregate (chat-coding-acceptance--field overall metric)))
          (cl-every
           (lambda (row)
             (>= (chat-coding-acceptance--field row metric)
                 (- aggregate 0.10)))
           rows)))
      metrics))))

(defun chat-coding-acceptance-quality-gates (metadata)
  "Return non-live quality gates recomputed from bounded METADATA."
  (let* ((facts (chat-coding-acceptance--field metadata 'qualityReliability))
         (semantic (chat-coding-acceptance--field facts 'semantic))
         (overall (chat-coding-acceptance--field semantic 'overall))
         (review (chat-coding-acceptance--field facts 'review))
         (prompt
          (chat-coding-acceptance--field
           facts 'planWorkNotePromptMedianRatio))
         (evidence (chat-coding-acceptance--field metadata 'evidence))
         (definition
          (chat-coding-acceptance--field overall 'definitionAccuracy))
         (precision
          (chat-coding-acceptance--field overall 'referencePrecision))
         (recall (chat-coding-acceptance--field overall 'referenceRecall))
         (top-five (chat-coding-acceptance--field overall 'topFiveHitRate))
         (review-recall (chat-coding-acceptance--field review 'recall))
         (review-precision (chat-coding-acceptance--field review 'precision)))
    (append
     (list
      (chat-coding-acceptance--reliability-gate
       "semantic-definition-accuracy" ">=98%" definition
       (chat-coding-acceptance--metric-valid-p definition)
       (and (numberp definition) (>= definition 0.98)))
      (chat-coding-acceptance--reliability-gate
       "semantic-reference-precision" ">=95%" precision
       (chat-coding-acceptance--metric-valid-p precision)
       (and (numberp precision) (>= precision 0.95)))
      (chat-coding-acceptance--reliability-gate
       "semantic-reference-recall" ">=90%" recall
       (chat-coding-acceptance--metric-valid-p recall)
       (and (numberp recall) (>= recall 0.90)))
      (chat-coding-acceptance--reliability-gate
       "semantic-top-five-hit-rate" ">=90%" top-five
       (chat-coding-acceptance--metric-valid-p top-five)
       (and (numberp top-five) (>= top-five 0.90)))
      (chat-coding-acceptance--reliability-gate
       "semantic-language-spread" "all 12 languages within 10 points"
       (chat-coding-acceptance--field semantic 'byLanguage)
       (chat-coding-acceptance--quality-language-metrics-valid-p semantic)
       (chat-coding-acceptance--quality-language-spread-p semantic)))
     (mapcar
      (lambda (group)
        (let* ((records
                (chat-coding-acceptance--field evidence (car group)))
               (expected (cddr group))
               (valid
                (chat-coding-acceptance--quality-test-records-shape-p
                 records expected))
               (passed
                (and valid
                     (chat-coding-acceptance--quality-tests-passed-p records))))
          (chat-coding-acceptance--reliability-gate
           (cadr group) "all directed scenarios passed"
           (and valid
                (format "%d/%d"
                        (seq-count
                         (lambda (record)
                           (eq t (chat-coding-acceptance--field
                                  record 'passed)))
                         (chat-coding-acceptance--sequence-list records))
                        (length expected)))
           valid passed
           "Run the exact directed scenario group from a clean checkout.")))
      chat-coding-acceptance-quality-scenarios)
     (list
      (chat-coding-acceptance--reliability-gate
       "plan-work-note-token-budget" "median <=5%" prompt
       (chat-coding-acceptance--metric-valid-p prompt)
       (and (numberp prompt) (<= prompt 0.05)))
      (chat-coding-acceptance--reliability-gate
       "review-critical-high-recall" ">=85%" review-recall
       (chat-coding-acceptance--metric-valid-p review-recall)
       (and (numberp review-recall) (>= review-recall 0.85)))
      (chat-coding-acceptance--reliability-gate
       "review-formal-precision" ">=80%" review-precision
       (chat-coding-acceptance--metric-valid-p review-precision)
       (and (numberp review-precision) (>= review-precision 0.80)))))))

(defun chat-coding-acceptance--metric-alist-equal-p (left right fields)
  "Return non-nil when LEFT and RIGHT agree for numeric FIELDS."
  (cl-every
   (lambda (field)
     (let ((lvalue (chat-coding-acceptance--field left field))
           (rvalue (chat-coding-acceptance--field right field)))
       (and (numberp lvalue) (numberp rvalue)
            (<= (abs (- lvalue rvalue)) 1e-9))))
   fields))

(defun chat-coding-acceptance--semantic-facts-match-p (actual recomputed)
  "Return non-nil when ACTUAL semantic facts equal RECOMPUTED facts."
  (let* ((fields '(definitionAccuracy referencePrecision
                   referenceRecall topFiveHitRate))
         (actual-overall
          (chat-coding-acceptance--field actual 'overall))
         (expected-overall
          (chat-coding-acceptance--field recomputed 'overall))
         (actual-rows
          (chat-coding-acceptance--sequence-list
           (chat-coding-acceptance--field actual 'byLanguage)))
         (expected-rows
          (chat-coding-acceptance--sequence-list
           (chat-coding-acceptance--field recomputed 'byLanguage))))
    (and
     (chat-coding-acceptance--metric-alist-equal-p
      actual-overall expected-overall fields)
     (= (length actual-rows) (length expected-rows))
     (cl-every
      (lambda (pair)
        (and
         (equal (chat-coding-acceptance--field (car pair) 'language)
                (chat-coding-acceptance--field (cdr pair) 'language))
         (chat-coding-acceptance--metric-alist-equal-p
          (car pair) (cdr pair) fields)))
      (cl-mapcar #'cons actual-rows expected-rows)))))

(defun chat-coding-acceptance--quality-facts-valid-p (metadata)
  "Return non-nil when quality facts in METADATA match raw evidence."
  (let* ((facts (chat-coding-acceptance--field metadata 'qualityReliability))
         (evidence (chat-coding-acceptance--field metadata 'evidence))
         (semantic
          (chat-coding-acceptance--semantic-summary
           (chat-coding-acceptance--field evidence 'semanticCorpus)))
         (review
          (chat-coding-acceptance--review-summary
           (chat-coding-acceptance--field evidence 'reviewCorpus)))
         (samples
          (chat-coding-acceptance--field
           (chat-coding-acceptance--field
            evidence 'planWorkNotePromptMedianRatio)
           'samples))
         (prompt
          (chat-coding-acceptance--plan-note-samples-median samples))
         (actual-prompt
          (chat-coding-acceptance--field
           facts 'planWorkNotePromptMedianRatio)))
    (and
     semantic review prompt
     (chat-coding-acceptance--semantic-facts-match-p
      (chat-coding-acceptance--field facts 'semantic) semantic)
     (chat-coding-acceptance--metric-alist-equal-p
      (chat-coding-acceptance--field facts 'review) review
      '(recall precision expectedCount reportedCount confirmedCount))
     (numberp actual-prompt)
     (<= (abs (- actual-prompt prompt)) 1e-9))))

(defun chat-coding-acceptance--quality-evidence-valid-p (metadata)
  "Return non-nil when METADATA contains all exact quality evidence."
  (let ((evidence (chat-coding-acceptance--field metadata 'evidence)))
    (and
     (chat-coding-acceptance--quality-facts-valid-p metadata)
     (cl-every
      (lambda (group)
        (let ((records
               (chat-coding-acceptance--field evidence (car group))))
          (and
           (chat-coding-acceptance--quality-test-records-shape-p
            records (cddr group))
           (chat-coding-acceptance--quality-tests-passed-p records))))
      chat-coding-acceptance-quality-scenarios))))

(defun chat-coding-acceptance--quality-gate-records-valid-p (metadata)
  "Return non-nil when METADATA carries exact recomputed quality gates."
  (let ((records
         (chat-coding-acceptance--sequence-list
          (chat-coding-acceptance--field metadata 'acceptanceGates)))
        (gates (chat-coding-acceptance-quality-gates metadata)))
    (and
     (= (length records) (length gates))
     (cl-every
      (lambda (pair)
        (let ((record (car pair)) (gate (cdr pair)))
          (and
           (equal (chat-coding-acceptance--field record 'name)
                  (chat-coding-acceptance-gate-name gate))
           (chat-coding-acceptance--passing-status-p
            (chat-coding-acceptance--field record 'status))
           (eq 'passed (chat-coding-acceptance-gate-status gate))
           (equal (chat-coding-acceptance--field record 'expected)
                  (chat-coding-acceptance-gate-expected gate))
           (equal (chat-coding-acceptance--field record 'actual)
                  (chat-coding-acceptance-gate-actual gate)))))
      (cl-mapcar #'cons records gates)))))

(defun chat-coding-acceptance-quality-record-gate
    (metadata expected-revision)
  "Validate complete quality METADATA for EXPECTED-REVISION."
  (let* ((schema (chat-coding-acceptance--field metadata 'schemaVersion))
         (revision
          (chat-coding-acceptance--field metadata 'implementationRevision))
         (tree-clean
          (chat-coding-acceptance--field metadata 'implementationTreeClean))
         (measured-at (chat-coding-acceptance--field metadata 'measuredAt))
         (records
          (chat-coding-acceptance--sequence-list
           (chat-coding-acceptance--field metadata 'acceptanceGates)))
         (valid
          (and (= (or schema 0) 1)
               (stringp expected-revision)
               (not (string-empty-p expected-revision))
               (equal revision expected-revision)
               (eq t tree-clean)
               (stringp measured-at)
               (not (string-empty-p measured-at))
               (chat-coding-acceptance--quality-gate-records-valid-p metadata)
               (chat-coding-acceptance--quality-evidence-valid-p metadata))))
    (chat-coding-acceptance-gate-create
     :name "quality-reliability-record"
     :status (if valid 'passed 'blocked)
     :expected "clean complete quality record for current implementation"
     :actual `((implementationRevision . ,revision)
               (expectedRevision . ,expected-revision)
               (treeClean . ,tree-clean)
               (gateCount . ,(length records)))
     :evidence
     (unless valid
       "Load the complete clean quality JSON for the current campaign revision."))))

(defun chat-coding-acceptance--canonical-test-names ()
  "Return exact canonical ERT names declared by the repository test files."
  (when-let* ((directory
               (expand-file-name
                "tests/unit" chat-coding-acceptance--repository-root))
              ((file-directory-p directory)))
    (let (names)
      (dolist (file (directory-files directory t "\\`test-.*\\.el\\'"))
        (with-temp-buffer
          (insert-file-contents file)
          (goto-char (point-min))
          (condition-case nil
              (while t
                (let ((form (read (current-buffer))))
                  (when (and (consp form)
                             (eq (car form) 'ert-deftest)
                             (symbolp (cadr form)))
                    (push (symbol-name (cadr form)) names))))
            (end-of-file nil))))
      (sort (delete-dups names) #'string<))))

(defun chat-coding-acceptance-canonical-record-gate
    (metadata expected-revision)
  "Validate canonical-suite METADATA for EXPECTED-REVISION."
  (let* ((schema (chat-coding-acceptance--field metadata 'schemaVersion))
         (revision
          (chat-coding-acceptance--field metadata 'implementationRevision))
         (tree-clean
          (chat-coding-acceptance--field metadata 'implementationTreeClean))
         (measured-at (chat-coding-acceptance--field metadata 'measuredAt))
         (summary (chat-coding-acceptance--field metadata 'summary))
         (records
          (chat-coding-acceptance--sequence-list
           (chat-coding-acceptance--field metadata 'tests)))
         (expected-names (chat-coding-acceptance--canonical-test-names))
         (recorded-names
          (mapcar
           (lambda (record)
             (chat-coding-acceptance--field record 'test))
           records))
         (total (chat-coding-acceptance--field summary 'total))
         (passed (chat-coding-acceptance--field summary 'passed))
         (failed (chat-coding-acceptance--field summary 'failed))
         (skipped (chat-coding-acceptance--field summary 'skipped))
         (unexpected (chat-coding-acceptance--field summary 'unexpected))
         (valid
          (and (equal schema 1)
               (stringp expected-revision)
               (not (string-empty-p expected-revision))
               (equal revision expected-revision)
               (eq t tree-clean)
               (stringp measured-at)
               (not (string-empty-p measured-at))
               expected-names
               (equal recorded-names expected-names)
               (seq-every-p
                (lambda (record)
                  (eq t (chat-coding-acceptance--field record 'passed)))
                records)
               (integerp total) (= total (length expected-names))
               (integerp passed) (= passed total)
               (equal failed 0)
               (equal skipped 0)
               (equal unexpected 0))))
    (chat-coding-acceptance-gate-create
     :name "canonical-suite-record"
     :status (if valid 'passed 'blocked)
     :expected "all exact canonical ERT tests passed on the clean current revision"
     :actual `((implementationRevision . ,revision)
               (expectedRevision . ,expected-revision)
               (treeClean . ,tree-clean)
               (expectedTests . ,(length expected-names))
               (recordedTests . ,(length records))
               (passed . ,passed)
               (failed . ,failed)
               (skipped . ,skipped)
               (unexpected . ,unexpected))
     :evidence
     (unless valid
       "Run tests/run-tests.el with CHAT_CANONICAL_OUTPUT on the clean current revision."))))

(defun chat-coding-acceptance-request-footprint-record-gate
    (record current-revision)
  "Validate request-footprint RECORD against CURRENT-REVISION and baseline."
  (let* ((baseline
          (chat-coding-acceptance--read-json-file
           chat-coding-acceptance--request-footprint-baseline-path))
         (baseline-revision (alist-get 'baselineRevision baseline))
         (baseline-bytes (alist-get 'combinedBytes baseline))
         (limit (alist-get 'maxCombinedRatio baseline))
         (record-revision
          (chat-coding-acceptance--field record 'implementationRevision))
         (record-baseline-revision
          (chat-coding-acceptance--field record 'baselineRevision))
         (record-baseline-bytes
          (chat-coding-acceptance--field record 'baselineCombinedBytes))
         (record-limit
          (chat-coding-acceptance--field record 'maxCombinedRatio))
         (current-bytes
          (chat-coding-acceptance--field record 'currentCombinedBytes))
         (record-ratio
          (chat-coding-acceptance--field record 'currentRatio))
         (reported-passed
          (chat-coding-acceptance--field record 'passed))
         (computed-ratio
          (and (numberp current-bytes) (numberp baseline-bytes)
               (> baseline-bytes 0)
               (/ (float current-bytes) baseline-bytes)))
         (within-limit
          (and (numberp computed-ratio) (numberp limit)
               (<= computed-ratio limit)))
         (valid
          (and record baseline current-revision
               (= (or (chat-coding-acceptance--field record 'schemaVersion) 0)
                  1)
               (equal record-revision current-revision)
               (eq t (chat-coding-acceptance--field
                      record 'implementationTreeClean))
               (equal record-baseline-revision baseline-revision)
               (equal record-baseline-bytes baseline-bytes)
               (equal record-limit limit)
               (numberp record-ratio)
               (numberp computed-ratio)
               (<= (abs (- record-ratio computed-ratio)) 1e-9)
               (assq 'passed record)
               (memq reported-passed '(t :json-false))
               (eq (eq t reported-passed) (and within-limit t)))))
    (chat-coding-acceptance-gate-create
     :name "first-request-footprint-record"
     :status (cond
              ((not valid) 'blocked)
              (within-limit 'passed)
              (t 'failed))
     :expected "clean revision-bound request footprint <=110% of frozen M9"
     :actual
     `((implementationRevision . ,record-revision)
       (baselineBytes . ,record-baseline-bytes)
       (currentBytes . ,current-bytes)
       (ratio . ,record-ratio)
       (limit . ,record-limit))
     :evidence
     (cond
      ((not valid)
       "Run tests/performance/run-request-footprint.el on the exact clean current revision.")
      ((not within-limit)
       "The measured first request exceeds the committed regression ceiling.")))))

(defun chat-coding-acceptance--single-implementation-revision (results)
  "Return the one nonempty implementation revision in RESULTS, or nil."
  (let ((revisions
         (delete-dups
          (delq nil
                (mapcar
                 (lambda (result)
                   (let ((revision
                          (chat-coding-acceptance--field
                           (chat-eval-result-metadata result)
                           'implementationRevision)))
                     (and (stringp revision)
                          (not (string-empty-p revision))
                          revision)))
                 results)))))
    (when (= (length revisions) 1) (car revisions))))

(defun chat-coding-acceptance--gate-check (gate)
  "Convert acceptance GATE to an immutable Eval check."
  (chat-eval-check
   (chat-coding-acceptance-gate-name gate)
   (eq (chat-coding-acceptance-gate-status gate) 'passed)
   (chat-coding-acceptance-gate-expected gate)
   `((status . ,(chat-coding-acceptance-gate-status gate))
     (value . ,(chat-coding-acceptance-gate-actual gate)))
   (chat-coding-acceptance-gate-evidence gate)))

(defun chat-coding-acceptance-overall-status (gates)
  "Return strict overall status for GATES."
  (cond
   ((seq-some (lambda (gate)
                (eq (chat-coding-acceptance-gate-status gate) 'failed))
              gates)
    'failed)
   ((seq-some (lambda (gate)
                (eq (chat-coding-acceptance-gate-status gate) 'blocked))
              gates)
    'blocked)
   (t 'passed)))

(defun chat-coding-acceptance-record (gates &optional metadata)
  "Persist one immutable final acceptance result from GATES and METADATA."
  (unless (and (listp gates)
               (seq-every-p #'chat-coding-acceptance-gate-p gates))
    (error "Acceptance requires typed gates"))
  (chat-eval-record-result
   :scenario-id "acceptance/m19"
   :scenario-revision 2
   :category "coding/acceptance"
   :fixture-id "m9-m19-roadmap"
   :fixture-digest
   (secure-hash
    'sha256
    (prin1-to-string
     (mapcar (lambda (gate)
               (list (chat-coding-acceptance-gate-name gate)
                     (chat-coding-acceptance-gate-expected gate)))
             gates)))
   :status (chat-coding-acceptance-overall-status gates)
   :checks (mapcar #'chat-coding-acceptance--gate-check gates)
   :metadata metadata))

(defun chat-coding-acceptance--percentile (values percentile)
  "Return nearest-rank PERCENTILE from numeric VALUES."
  (when values
    (let* ((ordered (sort (copy-sequence values) #'<))
           (rank (max 1 (ceiling (* percentile (length ordered))))))
      (nth (1- rank) ordered))))

(defun chat-coding-acceptance--heap-bytes ()
  "Return a comparable approximation of live Emacs heap bytes."
  (garbage-collect)
  (apply
   #'+
   (mapcar
    (lambda (entry)
      (if (and (numberp (nth 1 entry)) (numberp (nth 2 entry)))
          (* (nth 1 entry) (nth 2 entry))
        0))
    (garbage-collect))))

(defun chat-coding-acceptance--write-fixture (root file-count)
  "Create FILE-COUNT deterministic source files below ROOT."
  (let* ((directory-count (max 1 (ceiling (/ file-count 100.0))))
         (written 0))
    (dotimes (directory directory-count)
      (let ((path (expand-file-name (format "src/%04d" directory) root)))
        (make-directory path t)
        (dotimes (file 100)
          (when (< written file-count)
            (with-temp-file
                (expand-file-name (format "f%03d.py" file) path)
              (insert (format "def symbol_%04d_%03d(): return %d\n"
                              directory file written)))
            (cl-incf written)))))
    written))

(defun chat-coding-acceptance--environment ()
  "Return bounded benchmark environment facts."
  `((system . ,(symbol-name system-type))
    (systemConfiguration . ,system-configuration)
    (emacsVersion . ,emacs-version)
    (host . ,(system-name))))

(defun chat-coding-acceptance--measure-warm
    (root target file-count repetitions)
  "Measure warm query and context paths for ROOT and TARGET."
  (let (query-ms context-ms)
    (dotimes (index repetitions)
      (let ((started (float-time)))
        (chat-repo-map-query
         root
         (list
          :query
          (format "symbol_%04d_%03d"
                  (% index (max 1 (ceiling (/ file-count 100.0))))
                  (% index 100))
          :token-budget 2000 :limit 5))
        (push (* 1000.0 (- (float-time) started)) query-ms)))
    (let ((session (chat-code-session-create
                    "Acceptance benchmark" root target)))
      (setf (chat-code-session-context-strategy session) 'focused)
      (dotimes (_ repetitions)
        (let ((started (float-time)))
          (chat-context-code-build session)
          (push (* 1000.0 (- (float-time) started)) context-ms))))
    (list :warm-query-p95-ms
          (chat-coding-acceptance--percentile query-ms 0.95)
          :context-build-p95-ms
          (chat-coding-acceptance--percentile context-ms 0.95))))

(cl-defun chat-coding-acceptance-benchmark
    (&key (file-count chat-coding-acceptance-file-count)
          (repetitions chat-coding-acceptance-query-repetitions)
          on-complete)
  "Benchmark index, increment, query, context build, and memory.

ON-COMPLETE receives a bounded result plist.  The fixture is temporary and
is removed before the callback runs."
  (unless (and (integerp file-count) (> file-count 0)
               (integerp repetitions) (>= repetitions 20))
    (error "Benchmark requires positive files and at least 20 repetitions"))
  (let* ((root (make-temp-file "chat-repo-benchmark-" t))
         (fixture-digest
          (secure-hash
           'sha256
           (format "repo-map-v1:%d:python-symbol-template" file-count)))
         (before-bytes (chat-coding-acceptance--heap-bytes))
         (cold-start (float-time))
         cancel cleaned)
    (cl-labels
        ((cleanup
          ()
          (unless cleaned
            (setq cleaned t)
            (when (file-directory-p root)
              (chat-repo-map-discard root)
              (delete-directory root t))))
         (incremental-complete
         (cold cold-ms incremental incremental-start target)
          (let* ((incremental-ms
                  (* 1000.0 (- (float-time) incremental-start)))
                 (warm
                  (chat-coding-acceptance--measure-warm
                   root target file-count repetitions))
                 (result
                  (append
                   (list
                    :environment (chat-coding-acceptance--environment)
                    :fixture-digest fixture-digest
                    :file-count file-count :repetitions repetitions
                    :cold-index-ms cold-ms :cold-result cold
                    :incremental-ms incremental-ms
                    :incremental-result incremental)
                   warm
                   (list
                    :heap-delta-bytes
                    (max 0 (- (chat-coding-acceptance--heap-bytes)
                              before-bytes))))))
            (cleanup)
            (when on-complete (funcall on-complete result))))
         (cold-complete
          (cold)
          (let* ((cold-ms (* 1000.0 (- (float-time) cold-start)))
                 (target (expand-file-name "src/0000/f000.py" root))
                 (incremental-start (float-time)))
            (with-temp-file target
              (insert "def symbol_0000_000(): return 2\n"))
            (setq
             cancel
             (chat-repo-map-update-paths-async
              root (list target)
              (lambda (incremental)
                (incremental-complete
                 cold cold-ms incremental incremental-start target)))))))
      (chat-coding-acceptance--write-fixture root file-count)
      (setq cancel (chat-repo-map-refresh-async root #'cold-complete))
      (lambda ()
        (when (functionp cancel) (funcall cancel))
        (cleanup)))))

(cl-defun chat-coding-acceptance-benchmark-sync
    (&key (file-count chat-coding-acceptance-file-count)
          (repetitions chat-coding-acceptance-query-repetitions)
          (timeout 120))
  "Run the repository benchmark synchronously within TIMEOUT seconds."
  (let (result cancel)
    (setq cancel
          (chat-coding-acceptance-benchmark
           :file-count file-count :repetitions repetitions
           :on-complete (lambda (value) (setq result value))))
    (let ((deadline (+ (float-time) timeout)))
      (while (and (null result) (< (float-time) deadline))
        (accept-process-output nil 0.01)))
    (or result
        (progn
          (when (functionp cancel) (funcall cancel))
          (error "Repository benchmark timed out")))))

(defun chat-coding-acceptance-performance-gates (benchmark)
  "Return strict performance gates from BENCHMARK."
  (let* ((cold (plist-get benchmark :cold-result))
         (incremental (plist-get benchmark :incremental-result))
         (files (plist-get benchmark :file-count))
         (slice (max (or (plist-get cold :max-slice-wall-ms)
                         (plist-get cold :max-slice-ms)
                         0.0)
                     (or (plist-get incremental :max-slice-wall-ms)
                         (plist-get incremental :max-slice-ms)
                         0.0)))
         (query (plist-get benchmark :warm-query-p95-ms)))
    (list
     (chat-coding-acceptance-gate-create
      :name "performance-file-count"
      :status (if (and (= files 10000)
                       (= (plist-get cold :files) 10000)) 'passed 'failed)
      :expected 10000 :actual (plist-get cold :files))
     (chat-coding-acceptance-gate-create
      :name "performance-main-loop-slice"
      :status (if (<= slice 50.0) 'passed 'failed)
      :expected "<=50ms" :actual slice)
     (chat-coding-acceptance-gate-create
      :name "performance-warm-query-p95"
      :status (if (<= query 200.0) 'passed 'failed)
      :expected "<=200ms" :actual query)
     (chat-coding-acceptance-gate-create
      :name "performance-incremental-update"
      :status (if (= (plist-get incremental :changed) 1) 'passed 'failed)
      :expected 1 :actual (plist-get incremental :changed)))))

(defun chat-coding-acceptance-compare-live
    (baseline-directory current-directory
                        large-repo-baseline-directory
                        large-repo-current-directory)
  "Record a strict core and large-repository live comparison."
  (interactive
   (list (read-directory-name "M9 baseline results: ")
         (read-directory-name "M19 current results: ")
         (read-directory-name "M9 large-repo results: ")
         (read-directory-name "M19 large-repo results: ")))
  (let* ((baseline
          (chat-coding-acceptance-load-result-directory baseline-directory))
         (current
          (chat-coding-acceptance-load-result-directory current-directory))
         (large-repo-baseline
          (chat-coding-acceptance-load-result-directory
           large-repo-baseline-directory))
         (large-repo-current
          (chat-coding-acceptance-load-result-directory
           large-repo-current-directory))
         (result
          (chat-coding-acceptance-record
           (append
            (list
             (chat-coding-acceptance--campaign-directory-gate
              baseline-directory baseline "baseline")
             (chat-coding-acceptance--campaign-directory-gate
              current-directory current "current")
             (chat-coding-acceptance--campaign-directory-gate
              large-repo-baseline-directory large-repo-baseline
              "baseline" 1 5 "large-repo-baseline")
             (chat-coding-acceptance--campaign-directory-gate
              large-repo-current-directory large-repo-current
              "current" 1 5 "large-repo-current"))
            (chat-coding-acceptance-live-gates
             baseline current large-repo-baseline large-repo-current))
           `((baselineTrials . ,(length baseline))
             (currentTrials . ,(length current))
             (largeRepoBaselineTrials . ,(length large-repo-baseline))
             (largeRepoCurrentTrials . ,(length large-repo-current))
             (failureSummary .
                             ,(chat-coding-acceptance-failure-summary
                               current))))))
    (when (called-interactively-p 'interactive)
      (message "Live acceptance %s: %s"
               (chat-eval-result-status result)
               (chat-eval-result-id result)))
    result))

(defun chat-coding-acceptance-run-performance ()
  "Run and immutably record the standalone 10,000-file benchmark."
  (interactive)
  (let* ((benchmark (chat-coding-acceptance-benchmark-sync))
         (gates (chat-coding-acceptance-performance-gates benchmark))
         (result
          (chat-coding-acceptance-record
           gates
           `((kind . "performance")
             (environment . ,(plist-get benchmark :environment))
             (fixtureDigest . ,(plist-get benchmark :fixture-digest))
             (coldIndexMs . ,(plist-get benchmark :cold-index-ms))
             (incrementalMs . ,(plist-get benchmark :incremental-ms))
             (warmQueryP95Ms .
                             ,(plist-get benchmark :warm-query-p95-ms))
             (contextBuildP95Ms .
                                ,(plist-get benchmark
                                            :context-build-p95-ms))
             (heapDeltaBytes .
                             ,(plist-get benchmark :heap-delta-bytes))))))
    (when (called-interactively-p 'interactive)
      (message "Performance acceptance %s: %s"
               (chat-eval-result-status result)
               (chat-eval-result-id result)))
    result))

(cl-defun chat-coding-acceptance-run-final
    (&optional baseline-directory current-directory
               large-repo-baseline-directory large-repo-current-directory
               metadata quality-metadata canonical-metadata
               request-footprint-metadata)
  "Run and record the strict final acceptance gate set.

BASELINE-DIRECTORY and CURRENT-DIRECTORY contain immutable M9 and M19 live
Eval results.  LARGE-REPO-BASELINE-DIRECTORY and
LARGE-REPO-CURRENT-DIRECTORY contain the independently repeated one-task token
comparison.  Missing directories remain explicit blocked gates.  METADATA adds
the measured runtime reliability record.  QUALITY-METADATA adds measured
semantic, safety, isolation, context, and Review evidence.  CANONICAL-METADATA
adds the complete canonical ERT result record.  REQUEST-FOOTPRINT-METADATA adds
the no-network first-request measurement for the same clean revision."
  (interactive
   (list
    (let ((value
           (read-string "M9 baseline results directory (blank if missing): ")))
      (unless (string-empty-p value) value))
    (let ((value
           (read-string "M19 current results directory (blank if missing): ")))
      (unless (string-empty-p value) value))
    (let ((value
           (read-string "M9 large-repo results directory (blank if missing): ")))
      (unless (string-empty-p value) value))
    (let ((value
           (read-string "M19 large-repo results directory (blank if missing): ")))
      (unless (string-empty-p value) value))))
  (let* ((benchmark (chat-coding-acceptance-benchmark-sync))
         (baseline
          (and baseline-directory
               (file-directory-p baseline-directory)
               (chat-coding-acceptance-load-result-directory
                baseline-directory)))
         (current
          (and current-directory
               (file-directory-p current-directory)
               (chat-coding-acceptance-load-result-directory
                current-directory)))
         (large-repo-baseline
          (and large-repo-baseline-directory
               (file-directory-p large-repo-baseline-directory)
               (chat-coding-acceptance-load-result-directory
                large-repo-baseline-directory)))
         (large-repo-current
          (and large-repo-current-directory
               (file-directory-p large-repo-current-directory)
               (chat-coding-acceptance-load-result-directory
                large-repo-current-directory)))
         (current-revision
          (chat-coding-acceptance--single-implementation-revision current))
         (gates
          (append (chat-coding-acceptance-performance-gates benchmark)
                  (list
                   (chat-coding-acceptance--campaign-directory-gate
                    baseline-directory baseline "baseline")
                   (chat-coding-acceptance--campaign-directory-gate
                    current-directory current "current"))
                  (list
                   (chat-coding-acceptance--campaign-directory-gate
                    large-repo-baseline-directory large-repo-baseline
                    "baseline" 1 5 "large-repo-baseline")
                   (chat-coding-acceptance--campaign-directory-gate
                    large-repo-current-directory large-repo-current
                    "current" 1 5 "large-repo-current"))
                  (chat-coding-acceptance-live-gates
                   baseline current large-repo-baseline large-repo-current)
                  (list
                   (chat-coding-acceptance-reliability-record-gate
                    metadata current-revision))
                  (chat-coding-acceptance-reliability-gates metadata)
                  (list
                   (chat-coding-acceptance-quality-record-gate
                    quality-metadata current-revision))
                  (chat-coding-acceptance-quality-gates quality-metadata)
                  (list
                   (chat-coding-acceptance-canonical-record-gate
                    canonical-metadata current-revision)
                   (chat-coding-acceptance-request-footprint-record-gate
                    request-footprint-metadata current-revision))))
         (result
          (chat-coding-acceptance-record
           gates
           (append
            `((kind . "final")
              (baselineTrials . ,(length baseline))
              (currentTrials . ,(length current))
              (largeRepoBaselineTrials . ,(length large-repo-baseline))
              (largeRepoCurrentTrials . ,(length large-repo-current))
              (failureSummary .
                              ,(chat-coding-acceptance-failure-summary current))
              (environment . ,(plist-get benchmark :environment))
              (fixtureDigest . ,(plist-get benchmark :fixture-digest))
              (coldIndexMs . ,(plist-get benchmark :cold-index-ms))
              (incrementalMs . ,(plist-get benchmark :incremental-ms))
              (warmQueryP95Ms .
                                ,(plist-get benchmark :warm-query-p95-ms))
              (contextBuildP95Ms .
                                 ,(plist-get benchmark
                                             :context-build-p95-ms))
              (heapDeltaBytes .
                              ,(plist-get benchmark :heap-delta-bytes))
              (qualityEvidence . ,quality-metadata)
              (canonicalEvidence . ,canonical-metadata)
              (requestFootprintEvidence . ,request-footprint-metadata))
            metadata))))
    (when (called-interactively-p 'interactive)
      (message "Final acceptance %s: %s"
               (chat-eval-result-status result)
               (chat-eval-result-id result)))
    result))

(provide 'chat-coding-acceptance)
;;; chat-coding-acceptance.el ends here
